mongo:
  host:     localhost
  port:     27017
  db:       crnk
  user:		john
  password:	doe

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: ALL

  appenders:
    - type: console