:sectnums:

= Crnk Developer Guide
:toc: left
:toclevels: 3


Crnk is an implementation of the JSON API specification and recommendations in Java. It allows you to rapidly
build REST APIs without having to worry about lower protocol details and lets you focus on your application instead.
JSON API and Crnk come with support for:

- client and server implementation (with a focus on the later).
- url handling such as `/api/persons?filter[title]=John` and `/api/persons/{id}`
- sorting of resources
- filtering of resources
- pagination of result lists
- attaching link and meta information to data.
- inserting, updating and deleting of resources.
- support to request complex object graphs in a single request with JSON API inclusions.
- bulk updates with http://jsonpatch.com/[jsonpatch.com].
- a flexible module API to choose and extend the feature set of Crnk.
- eased testing with the client implementation providing type-safe stubs to access server repositories.
- repositories providing runtime/meta information about Crnk to implement, for example, documentation
  and UI automation.

Next to that Crnk support many popular frameworks and APIs:

- CDI: resolve repositories and extensions with CDI.
- Spring: run Crnk with Spring, including support for Spring Boot, Spring ORM and Spring Security.
- Servlet API: run Crnk as servlet.
- JAXRS: run Crnk as feature.
- JPA: expose entities as JSON API resources.
- bean validation: properly marshal validation and constraints exceptions.
- Zipkin: trace all your calls.

:leveloffset: 1

include::release_notes.adoc[]
include::architecture.adoc[]
include::setup.adoc[]
include::resource.adoc[]
include::repositories.adoc[]
include::client.adoc[]
include::modules.adoc[]
include::module_development.adoc[]

:leveloffset: 0