anchor:dataaccess[]


# Data Access

anchor:jpa_module[]

## JPA

The JPA module allows to automatically expose JPA entities as JSON:API repositories. No implementation
or Crnk-specific annotations are necessary.

The feature set includes:

- expose JPA entities to JSON:API repositories
- expose JPA relations as JSON:API repositories
- decide which entities to expose as endpoints
- sorting, filtering, paging, inclusion of related resources.
- all default operators of crnk are supported: `EQ`, `NEQ`, `LIKE`, `LT`, `LE`, `GT`, `GE`.
- filter, sort and include parameters can make use of the dot notation to
  join to related entities. For example, `sort=-project.name,project.id`,
   `filter[project.name][NEQ]=someValue` or `include=project.tasks`.
- support for entity inheritance by allowing sorting, filtering and inclusions
  to refer to attributes on subtypes.
- support for Jackson annotations to customize entity attributes on the JSON:API layer, see <<jackson_annotations,here>>.
- DTO mapping support to map entities to DTOs before sending them to clients.
- JPA Criteria API and QueryDSL support to issue queries.
- filter API to intercept and modify issued queries.
- support for computed attributes behaving like regular, persisted attributes.
- automatic transaction handling spanning requests and doing a rollback in case of an exception.
- `OptimisticLockExceptionMapper` mapped to JSON:API errors with
  `409` status code.
- `PersistenceException` and `RollbackException` are unwrapped
   to the usually more interesting exceptions like
   `ValidationException` and then translated to JSON:API errors.

Not yet supported are sparse field sets queried by tuple queries.

### JPA Module Setup

To use the JPA module, two things are necessary:

- a set of existing entities
- matching JPA repositories that have to be setup

For an  example have a look at
https://github.com/crnk-project/crnk-framework/tree/master/crnk-integration-examples/spring-boot-example[spring-boot-example].

#### Entity

Any JPA entity can be used to expose as JSON:API resource:

[source,java]
.ScheduleEntity.java
----
include::../../../../crnk-integration-examples/spring-boot-example/src/main/java/io/crnk/example/springboot/domain/model/ScheduleEntity.java[]
----

- Entities are mapped to resources.
- Crnk understands all JPA-related annotations and in many cases, not Crnk-specific annotations are necessary.
- Embeddables are mapped to nested json structures.
- Embeddables used as primary keys are mapped to/from a simple string to remain addressable as resource id. The order of attributes thereby determines the position
  of the values in the string.
- Not supported are relationships within embeddables.


It is possible to add additional JSON:API related fields to entities by annotating them with `@javax.persistence.Transient` (or the other way around by marking
it with `@JsonIgnore`).

[source,java]
.JpaTransientTestEntity.java
----
include::../../../../crnk-data/crnk-data-jpa/src/test/java/io/crnk/data/jpa/model/JpaTransientTestEntity.java[tags=docs]
----

`@JsonApiRelationId` is also supported for JPA entities:

[source,java]
----
	@Column(name="project_id")
	@JsonApiRelationId
	private Long projectId;

    @JsonApiRelation(serialize=SerializeType.ID_ONLY)
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", insertable = false, updatable = false)
	private Project project;
----

Notice that both fields are mapped to the same column. The `project` field must be made read-only with `insertable` and `updateable` to let JPA know that
`projectId` is supposed to be used for write operations. In the example, `SerializeType.ID_ONLY` will trigger for `projectId` to always be written to the
response in the relationship data section without having to fully load the related `project`.


#### JPA Repository Setup

To then expose
an entity as resource, provide a repository implementation inheriting from
`JpaEntityRepositoryBase`:

[source,java]
.ScheduleRepositoryImpl.java
----
include::../../../../crnk-integration-examples/spring-boot-example/src/main/java/io/crnk/example/springboot/domain/repository/ScheduleRepositoryImpl.java[]
----

If no such repository is specified, Spring Boot will by default expose all entities if not configured otherwise.


#### JPA module Setup

Crnk provides a Spring Boot AutoConfiguration to setup the JPA Module.
for more advanced use cases and other frameworks, the JPA module can also be setup
manually:

[source,java]
----
	TransactionRunner transactionRunner = ...;

	JpaModuleConfig config = new JpaModuleConfig();

	// expose all entitities from provided EntityManagerFactory
	config.exposeAllEntities(entityManagerFactory);

	JpaModule jpaModule = JpaModule.createServerModule(config, em, transactionRunner());

	CrnkFeature feature = new CrnkFeature(...);
	feature.addModule(jpaModule);
----

- `exposeAllEntities` takes an `EntityManagerFactory` and exposes all registered entities as
  JSON:API repository.
- `JpaRepositoryConfig.Builder.setRepositoryDecorator` allows to setup a repository decorator that can intercept and change any request,
  like setting up additional links and meta information.
- The transactionRunner needs to be implemented by the application to hook into the transaction processing of the used
  environment (Spring, JEE, etc.). This might be as simple as a Spring bean implementing `TransactionRunner` and carring a
  `@Transactional` annotation. The JPA module then ensures that every requests happens within such a transaction. Crnk
   comes with two default implementations: `SpringTransactionRunner` and
  `CdiTransactionRunner` that come are included in `crnk-setup-spring` and `crnk-cdi`.



### Pagination

The JPA module implements both pagination approaches supported by Crnk.
Setting `JpaModule.setTotalResourceCountUsed(true|false)` allows to decide whether the total
number of resources should be counted or whether just the presence of a subsequent resource
is checked (by querying `limit + 1` entities). By default the total resources
are counted. Have a look at the <<pagination>> section for more information.


### Criteria API and QueryDSL

The JPA module can work with two different query APIs, the default Criteria API
and QueryDSL. `JpaModule.setQueryFactory` allows
to choose between those two implementation. There is the `JpaCriteriaQueryFactory`
and the `QuerydslQueryFactory`. By default the Criteria API is used.
QueryDSL sits on top of JPQL and has to advantage of being easier to use.


### Lazy and Eager Loading

JPA relationships can either be `EAGER` or `LAZY`. The former is mapped to Crnk serialization type `ID_ONLY` and the later to `LAZY`.
If a relationship is supposed to be truly eager, `@JsonApiRelation(serializeType=SerializeType.EAGER)` can be used next to the JPA annotations.

Be careful with JPA since its default is `EAGER` loading. It is a typical source of performance issues.


### Access with Crnk client

To setup a Crnk client with the JPA module use:


[source,java]
----
	client = new CrnkClient(getBaseUri().toString());

	JpaModule module = JpaModule.newClientModule();
	setupModule(module, false);
	client.addModule(module);

	ResourceRepositoryV2<TaskEntity, UUID> genericRepo = client.getRepositoryForType(TypeEntity.class)
	TaskRepository typedRepo = client.getRepositoryForInterface(TaskRepository.class)
----

Have a look at https://github.com/crnk-project/crnk-framework/blob/master/crnk-data/crnk-data-jpa/src/test/java/io/crnk/data/jpa/data/JpaQuerySpecEndToEndTest.java within the `crnk-data-jpa`
test cases to see how everything is used together with `crnk-client`.

There is also the possibility to specify a repository interface. The interface has the benefit of providing proper typing of meta information,
link information and list return type. An example can look like:

[source,java]
----
public interface TaskRepository extends ResourceRepositoryV2<TaskEntity, UUID> {

	static class TaskListLinks implements LinksInformation, SelfLinksInformation {

		public String someLink = "test";

	}

	public static class TaskListMeta implements MetaInformation {

		public String someMeta = "test";

	}

	public class TaskList extends ResourceListBase<TaskEntity, TaskListMeta, TaskListLinks> {

	}

	@Override
	public TaskList findAll(QuerySpec querySpec);
}
----

On the server-side, the interface can be registered with:

[source,java]
----
  JpaRepositoryConfig.builder(PersonEntity.class)
           .setInterfaceClass(PersonRepository.class).build()
----


### Customizing the exposed resources over the underlying entity model

Not always it is desired to have a 1:1 mapping between resources and entities. There are
various techniques to customize the resource model:

- Make use of the Crnk and Jackson annotations like `@JsonApiResource`, `JsonApiRelationId`, `JsonApiRelation` and `@JsonIgnore` to modify the entities on the resource layer.
- Setup a DB view matching the desired resource and declare it as entity. This typically is the most efficient way to implement complex entity/resource mappings.
- Perform any kind of modification in your repository by overriding `findAll`, `save`, `create`,
  `delete`. Note that the repository itself must not necessarily return entity classes, but
   rather can also return a DTO.


### Standalone Usage

The given snipped shows how to translate a QuerySpec to a JPA Criteria query without involving
repositories and Crnk:

[source,java]
----
include::../../../../crnk-data/crnk-data-jpa/src/test/java/io/crnk/data/jpa/query/StandaloneQueryFactoryTest.java[tag=docs]
----



anchor:validation_module[]

## JSR 303 Validation Module

A `ValidationModule` provided by `io.crnk:crnk-validation` implements
resource validation and provides exception mappers for `javax.validation.ValidationException` and `javax.validation.ConstraintViolationException`.
Among others, it properly translates 'javax.validation.ConstraintViolation' instances to JSON:API errors.
A JSON:API error can, among others, contain a source pointer. This source pointer allows a clients/UI to
display the validation errors next to the corresponding input fields.

A translated exception can look like:

]
----
{
	"errors": [
		{
			"status": "422",
			"code": "javax.validation.constraints.NotNull",
			"title": "may not be null",
			"source": {
				"pointer": "data/attributes/name"
			},
			"meta": {
				"resourceId": "1",
				"type": "ConstraintViolation",
				"messageTemplate": "{javax.validation.constraints.NotNull.message}",
				"resourceType": "projects"
			}
		}
	]
}
----

Notice the `422` status code used for such errors.

As mentioned above, resource validation mechanism enabled by default will be applied in case of one of the following request
types: `POST`, `PUT` and `PATCH`. Once described behavior is unwanted,
module should be defined in the following way:

[source,java]
----
{
	@Bean
    ValidationModule validationModule()
        return ValidationModule.create(false);
    }
}
----

anchor:meta_module[]

## Meta Module

This is a module that exposes the internal workings of Crnk as JSON:API repositories.
It lets you browse the set of available resources, their types, their attributes, etc. For example,
Crnk UI make use of the meta module to implement auto-completing of input fields.

NOTE: There is currently no JSON:API standard for meta data. There are more
general formats like Swagger and ALPS. At some point those might be supported as
well (probably rather the later than the former). One
can view them to be complementary to the `MetaModule` as the later
is exactly tailored towards JSON:API, such as the accessability as regular
JSON:API (meta) repository and data structures matching the standard. Most likely,
any future standard implementation will built up on the information from the
`MetaModule`.

### Setup

A setup can look as follows:

[source,java]
----
		MetaModule metaModule = MetaModule.create();
		metaModule.addMetaProvider(new ResourceMetaProvider());
----

`ResourceMetaProvider` exposes all JSON:API resources and repositories as meta data. You may add further provides to
expose more meta data, such as the `JpaMetaProvider`.


### Examples

To learn more about the set of available resources, have a look at the `MetaElement` class and all its subclasses. Some of the
most important classes are:


[cols="15,15,70"]
|===
| Path              		| Implementation            | Description
| `/meta/element`			| `MetaElement` 			| Base class implemented by any meta element.
| `/meta/type`				| `MetaType` 				| Base class implemented by any meta type element.
| `/meta/primitiveType`		| `MetaPrimitiveType` 		| Represents primitive types like Strings and Integers.
| `/meta/arrayType`			| `MetaArrayType` 			| Represents an array type.
| `/meta/listType`			| `MetaListType` 			| Represents an list type.
| `/meta/setType`			| `MetaSetType` 			| Represents an set type.
| `/meta/mapType`			| `MetaMapType` 			| Represents an map type.
| `/meta/dataObject`		| `MetaDataObject`   		| Base type for any object holding data, like
																			 JPA entities or JSON:API resources.
| `/meta/attribute`			| `MetaAttribute` 			| Represents an attribute of a `MetaDataObject`.
| `/meta/resource`		 	| `MetaResource`   			| JSON:API resource representation extending `MetaDataObject`.
| `/meta/resourceRepository`| `MetaResourceRepository` 	| JSON:API repository representation holding resources.
|===

A `MetaResource` looks like:


]
----
{
    "id" : "resources.project",
    "type" : "meta/resource",
    "attributes" : {
      "name" : "Project",
      "resourceType" : "projects"
    },
    "relationships" : {
      "parent" : {
        ...
      },
      "interfaces" : {
        ...
      },
      "declaredKeys" : {
        ...
      },
      "children" : {
        ...
      },
      "declaredAttributes" : {
        ...
      },
      "subTypes" : {
        ...
      },
      "attributes" : {
        ...
      },
      "superType" : {
        ...
      },
      "elementType" : {
        ...
      },
      "primaryKey" : {
        ...
      }
    }
  }
----



A `MetaAttribute` looks like:

]
----
{
    "id" : "resources.project.name",
    "type" : "meta/resourceField",
    "attributes" : {
      "filterable" : true,
      "nullable" : true,
      "lazy" : false,
      "association" : false,
      "primaryKeyAttribute" : false,
      "sortable" : true,
      "version" : false,
      "insertable" : true,
      "meta" : false,
      "name" : "name",
      "updatable" : true,
      "links" : false,
      "derived" : false,
      "lob" : false,
      "cascaded" : false
    },
    "relationships" : {
      "parent" : {
        ...
      },
      "children" : {
        ...
      },
      "oppositeAttribute" : {
        ...
      },
      "type" : {
        ...
      }
    }
  }
----

### Identifiers for Meta Elements

Of importance is the assignment of IDs to meta elements. For resources the resource type is used to compute the meta
id and a `resources` prefix is added. In the example above, person gets a `resources.person` meta id.
Related objects (DTOs, links/meta info) located in the same or a subpackage of a resource gets the same meta id prefix.
A `ProjectData` sitting in a `dto` subpackage would get a `resources.dto.projectdata` meta id.

The meta ids are used, for example, by the Typescript generator to determine the file structure and dependencies of generated
source files.

Applications are enabled to adapt the id generator process with:

`new ResourceMetaProvider(idPrefix)`

and

`ResourceMetaProvider.putIdMapping(String packageName, String idPrefix)`

to override the default `resources` prefix and assign a specific prefix for a package.


### Extending the Meta Module

There is a `MetaModuleExtension` extension that allows other Crnk modules contribute `MetaProvider`
implementation. This allows to:

- add `MetaFilter` implementations to intercept and modify meta elements upon initialization and request.
- add `MetaPartition` implementations to introduce new, isolated areas in the meta model, like a JPA
  meta model next to the JSON:API one (like for documentation purposes).

For more detailed information have a look at the current `ResourceMetaProvider`.




## Activiti Module

NOTE: This module is in new and in incubation. Feedback and improvements welcomed.

There is an `ActivitiModule` for the https://www.activiti.org[Activiti] workflow engine that offers an alternative REST API.
The motivation of `ActivitiModule` is to:

- have a JSON:API compliant REST API to benefit from the resource-oriented architecture, linking, sorting, filtering, paging,
  and client-side tooling of JSON:API.
- have a type-safe, non-generic REST API that is tailored towards the use cases at hand. This means that for each process
  and task definition, there is a dedicated repository and resource type for it. The resource is comprised of
  both the static fields provided by Activiti (like `name`, `startTime` and `priority`) and the dynamic fields
  stored by the application as process/task/form variables. Mapping to static resp. dynamic fields is done
  automatically by the `ActivitiModule` and hidden from consumers. The repository implementations ensure a proper isolation of different types. And
  the application is enabled, for example, to introduce custom security policies for each resource with
  the `SecurityModule` or a `ResourceFilter`.

This setup differs substantially from the API provided by Activiti that is implemented
in generic fashion.

### Setup

The `ActivitiModule` comes within a small example application within the `src/main/test` directory that showcases its use.
It sets up an approval flow where changes to the `Schedule` resource must be approved by a user.

The `ActivitiModule` implements four resource base classes that match the equivalent Activiti classes:

- `ExecutionResource`
- `FormResource`
- `ProcessInstanceResource`
- `TaskResource`

To setup a JSON:API repository for a process or task, the corresponding resource class can be subclassed and extended with
the application specific fields. For example:

[source,java]
.ApprovalProcessInstance.java
----
include::../../../../crnk-data/crnk-data-activiti/src/test/java/io/crnk/data/activiti/example/approval/ApprovalProcessInstance.java[tag=docs1]
	...
include::../../../../crnk-data/crnk-data-activiti/src/test/java/io/crnk/data/activiti/example/approval/ApprovalProcessInstance.java[tag=docs2]
----

and

[source,java]
.ScheduleApprovalProcessInstance.java
----
include::../../../../crnk-data/crnk-data-activiti/src/test/java/io/crnk/data/activiti/example/model/ScheduleApprovalProcessInstance.java[tag=docs1]
	...
include::../../../../crnk-data/crnk-data-activiti/src/test/java/io/crnk/data/activiti/example/model/ScheduleApprovalProcessInstance.java[tag=docs2]
----

The example application makes use of an intermediate `ApprovalProcessInstance` base class to potentially share the approval
logic among multiple entities in the future (if it would be real-world use case). `ScheduleApprovalProcessInstance` has
the static fields of Activiti and a number of custom, dynamic fields like `resourceType`, `resourceId` and `newValues`.
The dynamic fields will be mapped to to process, task resp. form variables.

Notice the relation to `ApproveTask`, which is a task counter part extending from `TaskResource`. If a process has multiple
tasks, you may introduce multiple such relationships.

Finally, the setup of the `ActiviModule` looks like:

[source,java]
.ApprovalTestApplication.java
----
include::../../../../crnk-data/crnk-data-activiti/src/test/java/io/crnk/data/activiti/example/ApprovalTestApplication.java[tag=activitiModule]
----

- `ActivitiModuleConfig` allows to register processes and tasks that then will be exposed as repositories.
- `ScheduleApprovalProcessInstance`, `ApproveTask` and the `approveTask` relationship are registered.
- `ApproveTask` is user task that is handled by submitting an `ApproveForm`.
- `filterByProcessDefinitionKey` and `filterByTaskDefinitionKey` ensure that the two repositories
  are isolated from other repositories for `GET`, `POST`, `PATCH` and `DELETE` operations.

One could imagine to make this configuration also available through an annotation-based API in the future as it is
closely related to the resource classes and fields.


### Example application

The example application goes a few steps further in the setup. The patterns of those steps might be of
interest of consumers of the `ActivitiModule` as well.

The workflow looks as follows:

]
.approval.bpmn20.xml
----
include::../../../../crnk-data/crnk-data-activiti/src/test/resources/approval.bpmn20.xml[]
----

There is a:

- `approveScheduleTask` task requires a form submission by a user.
- `approvalExclusiveGateway` checks whether the change was accepted.
- `scheduleChangeApproved` invokes `${approvalManager.approved(execution)}` whereas `approvalManager` is a Java object
  taking care of the approval handling and registered to `activiti.cfg.xml`.
- `approvalManager.approved(...)` reconstructs the original request and forwards it to Crnk again to save the approved
  changes. This means the regular `ScheduleRepository` implementation will be called in the same fashion as for
   a typical request. Real world use cases may also need to save and reconstruct the security context.

For the approval-related functionality a second module is registered:

[source,java]
.ApprovalTestApplication.java
----
include::../../../../crnk-data/crnk-data-activiti/src/test/java/io/crnk/data/activiti/example/ApprovalTestApplication.java[tag=approvalModule]
----

- `ApprovalRepositoryDecorator` hooks into the request processing of the Crnk engine and intercepts
 all `PATCH` and `POST` requests for the `Schedule` resource. The decorator then may chooses to
 abort the request and start an approval flow instead with the help of `ApprovalManager`.
- `ApprovalRelationshipRepository` introduces an additional relationship between the actual resources
  and approval resources. It can be used, for example, by user interfaces to show the current status
  of an open approval workflow. `ApprovalRelationshipRepository.getResourceFields` declares
  the relationship field, meaning that the original application resource does not have to declare the
  relationship. This may or may not be useful depending on how much control there is over the original resource
  (for example there is no control over JPA entities).
- `historic(...)` method specify the historic resource counterparts to query the history.

The chosen setup leads to an approval system that is *fully transparent* to the actual repository implementations
and can be added to any kind of repository.

`ApprovalIntTest` showcases the example workflow by doing a change,
starting the approval process, submitting a form and then verifying the changes have been saved.


### Limitations

- Currently the main entities of Activiti have been exposed. Configuration-related repositories
  could be exposed as well in the future.
- Historic repositories are still considered being experimental.
- Activiti has a limited query API that is inherited by the application. Potentially `crnk-data-jpa` could help
  out a bit in this area.
- Multi-tenancy is not yet done out-of-the-box.
- Activiti has been forked to Flowable. As of yet it is unclear whether one or both project
  will survive in the long-term.




anchor:facet_module[]

## Faceted Search

WARNING: This feature is new and considered experimental. Also have a look at the roadmap.

Faceted search is used by many UIs to allow users to quickly navigate data sets. For example, virtually
every online shop makes use of the feature to show product categories and the number of products in that
category. Those categories, denoted as facets, have a label, a set of values and a count for each value. Facets
may also depend on each other, whereas later facets are filtered by preceding ones. With `FacetModule` Crnk
provides an out-of-the-box solution to implement faceted search.


### Setup

To setup faceted search, the `FacetModule` must be added to  application. For Spring Boot there is
a `CrnkFacetAutoConfiguration` in place. To then enable faceted search for an attribute, it can be
annotated with `@Facet`:

[source,java]
.FacetedProject.java
----
include::../../../../crnk-data/crnk-data-facet/src/test/java/io/crnk/data/facet/setup/FacetedProject.java[tag=docs]
----

Behind the scenes there are currently two implementations available that are automatically chosen based on the repository at hand:

- `InMemoryFacetProvider` that queries all resources and computes the facets in-memory. Only *suitable for small data sets*!
- `JpaFacetProvider` that makes use of SQL `GROUP BY` queries to efficiently compute facets. Used for any JPA-backed repository.

For very large data sets, the use of ElasticSearch is recommended (not yet implemented). Applications are also free to
implement their own `FacetProvider` implementation and register it through `FacetModuleExtension`.

### Examples

All the facets are then available as regular, new JSON:API resource that can filtered, paged, sorted, etc. like
any other resource:

]
.http://127.0.0.1:8080/api/facet
----
{

  "data" : [ {
    "id" : "projects_name",
    "type" : "facet",
    "attributes" : {
      "values" : {
        "Some Project" : {
          "label" : "Some Project",
          "value" : "Some Project",
          "filterSpec" : {
            "path" : "name",
            "operator" : "EQ",
            "value" : "Some Project",
          },
          "count" : 1
        },
        ...
      },
      "name" : "name",
      "type" : "projects",
      "labels" : [ "Great Project", "Crnk Project", "Some Project", "JSON:API Project" ]
    },
  }]
}
----

Note that the values are ordered by their count in the `labels` attribute.


### Nesting

To select values of facets and update the counts of subsequent facets use:

----
http://127.0.0.1:8080/api/facet?filter[values.priority][SELECT]=1,2
----

A facet value is selected through its label and the `SELECT` operator. In the given example, the priority
gets restricted to `1` and `2`. This in turn restricts the counts of facets that follow
the `priority` facet. To choose and order facets use:

----
http://127.0.0.1:8080/api/facet?filter[name]=priority,name
----

Facets are then ordered as specified by `filter[name]`.

For more examples, see `InMemoryFacetProviderTest`.

### Grouping

To compute facets separately for each label of a particular facet, use the `GROUP` operator:

----
http://127.0.0.1:8080/api/facet?filter[values][GROUP]=priority,name
----

It works equivalent to SQL `GROUP BY` queries. In the example a count is computed for every pair of `priority` and `name`
and returned as facet resource.

WARNING: the GROUP operator needs for further performance tuning.



### Roadmap

- Limit number of facet values and introduce a "other" category.
- Configurable null handling.
- Data/time support.
- Range-based facets.
- Native Elastic Search implementation

Feedback and PRs welcomed!
