anchor:dataaccess[]


# Data Access

anchor:jpa_module[]

## JPA

The JPA module allows to automatically expose JPA entities as JSON API repositories. No implementation
or Crnk-specific annotations are necessary.

The feature set includes:

- expose JPA entities to JSON API repositories
- expose JPA relations as JSON API repositories
- decide which entities to expose as endpoints
- sorting, filtering, paging, inclusion of related resources.
- all default operators of crnk are supported: `EQ`, `NEQ`, `LIKE`, `LT`, `LE`, `GT`, `GE`.
- filter, sort and include parameters can make use of the dot notation to
  join to related entities. For example, `sort=-project.name,project.id`,
   `filter[project.name][NEQ]=someValue` or `include=project.tasks`.
- support for entity inheritance by allowing sorting, filtering and inclusions
  to refer to attributes on subtypes.
- support for Jackson annotations to customize entity attributes on the JSON API layer, see <<jackson_annotations,here>>.
- DTO mapping support to map entities to DTOs before sending them to clients.
- JPA Criteria API and QueryDSL support to issue queries.
- filter API to intercept and modify issued queries.
- support for computed attributes behaving like regular, persisted attributes.
- automatic transaction handling spanning requests and doing a rollback in case of an exception.
- `OptimisticLockExceptionMapper` mapped to JSON API errors with
  `409` status code.
- `PersistenceException` and `RollbackException` are unwrapped
   to the usually more interesting exceptions like
   `ValidationException` and then translated to JSON API errors.

Have a look at the Spring Boot example application which makes use of the JPA module, DTO mapping
and computed attributes.

Not yet supported are sparse field sets queried by tuple queries.

### JPA Module Setup

To use the module, add a dependency to `io.crnk:crnk-jpa` and register the `JpaModule`
to Crnk. For example in the case of JAX-RS:

[source]
----
	TransactionRunner transactionRunner = ...;

	JpaModuleConfig config = new JpaModuleConfig();

	// expose all entitities from provided EntityManagerFactory
	config.exposeAllEntities(entityManagerFactory);

	// expose single entity
    config.addRepository(JpaRepositoryConfig.builder(TaskEntity.class).build());

    // expose single entity with additional interface declaration. Interface is used to
    // extract the list, meta and link information types.
    config.addRepository(
      JpaRepositoryConfig.builder(PersonEntity.class)
           .setInterfaceClass(PersonRepository.class).build()
    );

	JpaModule jpaModule = JpaModule.createServerModule(config, em, transactionRunner());

	CrnkFeature feature = new CrnkFeature(...);
	feature.addModule(jpaModule);
----


The JPA modules by default looks up the entityManagerFactory and obtains a list
of registered JPA entities. For each entity a instance of `JpaEntityRepository`
is registered to Crnk using the module API. Accordingly, every relation
is registered as `JpaRelationshipRepository`.

- `JpaModuleConfig.setRepositoryFactory` allows to provide a factory to change or customized the used repositories.
- `exposeAllEntities` takes an `EntityManagerFactory` and exposes all registered entities as
  JSON API repository.
- To manually select the entities exposed to Crnk use `JpaModuleConfig.addRepository(...)`.
 `JpaRepositoryConfig` provides a number of customization options for the exposed entity.
  `setListClass`, `setListMetaClass` and `setListLinksClass` allow to set the type information and will
  then return resources having lists, links and meta data of the given type.  `setInterfaceClass`
  is a shortcut that allows to extract those three types from a repository interface definition
  (see `TaskRepository` below for an example).
- `JpaRepositoryConfig.Builder.setRepositoryDecorator` allows to setup a repository decorator that allows to intercept
  the request and responses and perform changes, like setting up additional links and meta information.
- `JpaRepositoryConfig` allows to specify DTO mapping, have a look at the later section to this topic.
- Internally the JpaModule will create instances of `JpaResourceRepository` and  `JpaRelationshipRepository`
  to register them
- The transactionRunner needs to be implemented by the application to hook into the transaction processing of the used
  environment (Spring, JEE, etc.). This might be as simple as a Spring bean implementing `TransactionRunner` and adding a
  `@Transactional` annotation. The JPA module makes sure that every call to a repository happens within such a transaction
  boundary. Crnk comes with two default implementations: `SpringTransactionRunner` and
  `CdiTransactionRunner` that come are included in `crnk-setup-spring` and `crnk-cdi`.


### JPA Entity Setup

Most features of JPA are supported and get mapped to JSON API:

- Entities are mapped to resources.
- Embeddables are mapped to nested json structures.
- Embeddables used as primary keys are mapped to/from a simple string to remain addressable as resource id. The order of attributes thereby determines the position
  of the values in the string.
- Not yet supported are relationships within embeddables.

It is possible to add additional JSON API related fields to entities by making use of the `@Transient` annotation of `javax.persistence` (or the other way around by marking
it with `@JsonIgnore`):

[source]
.JpaTransientTestEntity.java
----
include::../../../../crnk-jpa/src/test/java/io/crnk/jpa/model/JpaTransientTestEntity.java[tags=docs]
----

However, for more complex scenarios application may rather make use of <<dto_mapping,DTO mapping>>.


### JPA Setup with Spring

Have a look at <<jpa_spring,JPA Module Auto Configuration>>. For Spring Boot an auto configuration is
available that already takes care of some defaults.


### Pagination

The JPA module implements both pagination approaches supported by Crnk.
Setting `JpaModule.setTotalResourceCountUsed(true|false)` allows to decide whether the total
number of resources should be counted or whether just the presence of a subsequent resource
is checked (by querying `limit + 1` entities). By default the total resources
are counted. Have a look at the <<pagination>> section for more information.


### Criteria API and QueryDSL

The JPA module can work with two different query APIs, the default Criteria API
and QueryDSL. `JpaModule.setQueryFactory` allows
to choose between those two implementation. There is the `JpaCriteriaQueryFactory`
and the `QuerydslQueryFactory`. By default the Criteria API is used.
QueryDSL sits on top of JPQL and has to advantage of being easier to use.


### Access with Crnk client

To setup a Crnk client with the JPA module use:


[source]
----
	client = new CrnkClient(getBaseUri().toString());

	JpaModule module = JpaModule.newClientModule();
	setupModule(module, false);
	client.addModule(module);

	ResourceRepositoryV2<TaskEntity, UUID> genericRepo = client.getRepositoryForType(TypeEntity.class)
	TaskRepository typedRepo = client.getRepositoryForInterface(TaskRepository.class)
----

Have a look at https://github.com/crnk-project/crnk-framework/blob/develop/crnk-jpa/src/test/java/io/crnk/jpa/JpaQuerySpecEndToEndTest.java within the `crnk-jpa`
test cases to see how everything is used together with `crnk-client`.

There is also the possibility to specify a repository interface. The interface has the benefit of providing proper typing of meta information,
link information and list return type. An example can look like:

[source]
----
public interface TaskRepository extends ResourceRepositoryV2<TaskEntity, UUID> {

	static class TaskListLinks implements LinksInformation, SelfLinksInformation {

		public String someLink = "test";

	}

	public static class TaskListMeta implements MetaInformation {

		public String someMeta = "test";

	}

	public class TaskList extends ResourceListBase<TaskEntity, TaskListMeta, TaskListLinks> {

	}

	@Override
	public TaskList findAll(QuerySpec querySpec);
}
----

On the server-side, the interface can be registered with:

[source]
----
  JpaRepositoryConfig.builder(PersonEntity.class)
           .setInterfaceClass(PersonRepository.class).build()
----

### Intercepting and modifying requests to JPA repositories

JPA repositories support the same set of <<repository_decoration,decoration>> and <<requestfilter,filtering>> mechanisms as any other repository.
They allow to intercept and customize request before or after hitting the JPA repositories.

Next to that, there are further JPA-specific filters that allow to apply changes to JPA repository requests:

`JpaModuleConfig.addFilter(new MyRepositoryFilter())`

A filter looks like:

[source]
----
	public class MyRepositoryFilter extends JpaRepositoryFilterBase {

		boolean accept(Class<?> resourceType){...}

		<T, I extends Serializable> JpaEntityRepository<T, I> filterCreation(JpaEntityRepository<T, I> repository){...}

		QuerySpec filterQuerySpec(Object repository, QuerySpec querySpec){...}

		...
	}
----

The filter methods can perform any kind of customizations. With `JpaCriteriaRepositoryFilter` and `QuerydslRepositoryFilter` there are two specialization of
`JpaRepositoryFilter` that allow further customizations specific to respective query mechanism.


### Customizing the exposed resources over the underlying entity model

Not always it is desired to have a 1:1 mapping between resources and entities. There are various techniques to customize the resource model:

- Make use of the Crnk and Jackson annotations like `@JsonApiResource`, `JsonApiRelationId`, `JsonApiRelation` and `@JsonIgnore` to modify the entities on the resource layer.
- Setup a DB view matching the desired resource and declare it as entity. This typically is the most efficient way to implement complex entity/resource mappings.
- Setup a DTO mapping to map entities to resource objects (see the subsequent section for more information)

#### DTP Mapping

anchor:dto_mapping[]

Mapping to DTO objects is supported with `JpaModule.registerMappedEntityClass(...)`.
A mapper then can be provided that translates the Entity to a DTO class.
Such a mapper might be implemented manually or generated (mostly) automatically
with tools like MapStruct. If two mapped entities are registered, there
respective mapped relationships will be automatically registered as well.

The mapping is performed by `JpaMapper` interface providing methods to
map and unmap entities to and from DTOs. There is an additional
`unmapQuerySpec` method that does the same task for query parameters,
such as renaming attributes or translating types.
`JpaMapper` may introduce and fill-up new attributes not available on one side.
Such attributes can either be set in the mapper itself, or
be derived from a value computed in the database as shown in this example:

[source]
----
    JpaModuleConfig config = new JpaModuleConfig();
	config.setQueryFactory(QuerydslQueryFactory.newInstance());

	// introduce new computed attribute
	QuerydslExpressionFactory<QTestEntity> basicComputedValueFactory = new QuerydslExpressionFactory<QTestEntity>() {

		@Override
		public Expression<String> getExpression(QTestEntity parent, JPAQuery<?> jpaQuery) {
			return parent.stringValue.upper();
		}
	};
	QuerydslQueryFactory queryFactory = (QuerydslQueryFactory) config.getQueryFactory();
	queryFactory.registerComputedAttribute(TestEntity.class, TestDTO.ATTR_COMPUTED_UPPER_STRING_VALUE,
		 String.class, basicComputedValueFactory);

	// register repository with DTO mapping
	config.addRepository(
	  JpaRepositoryConfig.builder(TestEntity.class, TestDTO.class, new TestDTOMapper(entityManager)).build()
	);

    JpaModule module = JpaModule.createServerModule(config, em, transactionRunner);
----

and

[source]
----
	public class TestDTOMapper implements JpaMapper<TestEntity, TestDTO> {

		private EntityManager em;

		...

		@Override
		public TestDTO map(Tuple tuple) {
			TestDTO dto = new TestDTO();
			TestEntity entity = tuple.get(0, TestEntity.class);
			dto.setId(entity.getId());
			dto.setStringValue(entity.getStringValue());
			dto.setComputedUpperStringValue(tuple.get("computedUpperStringValue", String.class));
			...
			return dto;
		}

		@Override
        public TestEntity unmap(TestDto dto) {
        	TestEntity entity = em.find(TestEntity.class, dto.getId());
        	if(entity == null){
        	  entity = new TestEntity();
        	}
        	entity.setStringValue(dto.getStringValue());

        	...
        }

        @Override
        public QuerySpec unmapQuerySpec(QuerySpec querySpec) {
           	...
        }
	}
----

The example shows:
- Some of the regular entity attributes are mapped to the DTO.
- There is a `computedUpperStringValue` attribute that is computed with an SQL expression.
  The expression can be written with the Criteria API or QueryDSL depending
  on which query backend is in use.
- `unmap` looks up the entity with the `EntityManager`. This is necessary to obtain a JPA-managed
  instance. Otherwise a JPA implementation may treat existing entities as new entities and fail
  upon insertion.

Computed attributes are indistinguishable from regular, persisted entity attributes.
They can be used for selection, sorting and filtering. Both `JpaCriteriaQueryFactory`
and `QuerydslQueryFactory` provide a `registerComputedAttribute` method to
register an expression factory to create such computed attributes. The registration requires
the target entity and a name. To make the computed attribute available
to consumers, the mapper class has access to it trough the provided
tuple class. Have a look at https://github.com/crnk-project/crnk-framework/blob/master/crnk-jpa/src/test/java/io/crnk/jpa/mapping/DtoMappingTest.java to see everything in use.

There is currently not yet any automated support for renaming of attribute. If attributes
are renamed on DTOs, the incoming QuerySpec has to be modified accordingly to
match again the entity attribute naming. The same holds for types like Enums or dates. The
JPA implementation mostly likely will fail with an incorrect type is passed to it.


anchor:validation_module[]

## JSR 303 Validation Module

A `ValidationModule` provided by `io.crnk:crnk-validation` implements
resource validation and provides exception mappers for `javax.validation.ValidationException` and `javax.validation.ConstraintViolationException`.
Among others, it properly translates 'javax.validation.ConstraintViolation' instances to JSON API errors.
A JSON API error can, among others, contain a source pointer. This source pointer allows a clients/UI to
display the validation errors next to the corresponding input fields.

A translated exception can look like:

[source]
----
{
	"errors": [
		{
			"status": "422",
			"code": "javax.validation.constraints.NotNull",
			"title": "may not be null",
			"source": {
				"pointer": "data/attributes/name"
			},
			"meta": {
				"resourceId": "1",
				"type": "ConstraintViolation",
				"messageTemplate": "{javax.validation.constraints.NotNull.message}",
				"resourceType": "projects"
			}
		}
	]
}
----

Notice the `422` status code used for such errors.

As mentioned above, resource validation mechanism enabled by default will be applied in case of one of the following request
types: `POST`, `PUT` and `PATCH`. Once described behavior is unwanted,
module should be defined in the following way:

[source]
----
{
	@Bean
    ValidationModule validationModule()
        return ValidationModule.create(false);
    }
}
----



anchor:meta_module[]

## Meta Module

This is a module that exposes the internal workings of Crnk as JSON API repositories.
It lets you browse the set of available resources, their types, their attributes, etc. For example,
Crnk UI make use of the meta module to implement auto-completing of input fields.

NOTE: There is currently no JSON API standard for meta data. There are more
general formats like Swagger and ALPS. At some point those might be supported as
well (probably rather the later than the former). One
can view them to be complementary to the `MetaModule` as the later
is exactly tailored towards JSON API, such as the accessability as regular
JSON API (meta) repository and data structures matching the standard. Most likely,
any future standard implementation will built up on the information from the
`MetaModule`.

### Setup

A setup can look as follows:

[source]
----
		MetaModule metaModule = MetaModule.create();
		metaModule.addMetaProvider(new ResourceMetaProvider());
----

`ResourceMetaProvider` exposes all JSON API resources and repositories as meta data. You may add further provides to
expose more meta data, such as the `JpaMetaProvider`.


### Examples

To learn more about the set of available resources, have a look at the `MetaElement` class and all its subclasses. Some of the
most important classes are:


[cols="15,15,70"]
|===
| Path              		| Implementation            | Description
| `/meta/element`			| `MetaElement` 			| Base class implemented by any meta element.
| `/meta/type`				| `MetaType` 				| Base class implemented by any meta type element.
| `/meta/primitiveType`		| `MetaPrimitiveType` 		| Represents primitive types like Strings and Integers.
| `/meta/arrayType`			| `MetaArrayType` 			| Represents an array type.
| `/meta/listType`			| `MetaListType` 			| Represents an list type.
| `/meta/setType`			| `MetaSetType` 			| Represents an set type.
| `/meta/mapType`			| `MetaMapType` 			| Represents an map type.
| `/meta/dataObject`		| `MetaDataObject`   		| Base type for any object holding data, like
																			 JPA entities or JSON API resources.
| `/meta/attribute`			| `MetaAttribute` 			| Represents an attribute of a `MetaDataObject`.
| `/meta/resource`		 	| `MetaResource`   			| JSON API resource representation extending `MetaDataObject`.
| `/meta/resourceRepository`| `MetaResourceRepository` 	| JSON API repository representation holding resources.
|===

A `MetaResource` looks like:


[source]
----
{
    "id" : "resources.project",
    "type" : "meta/resource",
    "attributes" : {
      "name" : "Project",
      "resourceType" : "projects"
    },
    "relationships" : {
      "parent" : {
        ...
      },
      "interfaces" : {
        ...
      },
      "declaredKeys" : {
        ...
      },
      "children" : {
        ...
      },
      "declaredAttributes" : {
        ...
      },
      "subTypes" : {
        ...
      },
      "attributes" : {
        ...
      },
      "superType" : {
        ...
      },
      "elementType" : {
        ...
      },
      "primaryKey" : {
        ...
      }
    }
  }
----



A `MetaAttribute` looks like:

[source]
----
{
    "id" : "resources.project.name",
    "type" : "meta/resourceField",
    "attributes" : {
      "filterable" : true,
      "nullable" : true,
      "lazy" : false,
      "association" : false,
      "primaryKeyAttribute" : false,
      "sortable" : true,
      "version" : false,
      "insertable" : true,
      "meta" : false,
      "name" : "name",
      "updatable" : true,
      "links" : false,
      "derived" : false,
      "lob" : false,
      "cascaded" : false
    },
    "relationships" : {
      "parent" : {
        ...
      },
      "children" : {
        ...
      },
      "oppositeAttribute" : {
        ...
      },
      "type" : {
        ...
      }
    }
  }
----

### Identifiers for Meta Elements

Of importance is the assignment of IDs to meta elements. For resources the resource type is used to compute the meta
id and a `resources` prefix is added. In the example above, person gets a `resources.person` meta id.
Related objects (DTOs, links/meta info) located in the same or a subpackage of a resource gets the same meta id prefix.
A `ProjectData` sitting in a `dto` subpackage would get a `resources.dto.projectdata` meta id.

The meta ids are used, for example, by the Typescript generator to determine the file structure and dependencies of generated
source files.

Applications are enabled to adapt the id generator process with:

`new ResourceMetaProvider(idPrefix)`

and

`ResourceMetaProvider.putIdMapping(String packageName, String idPrefix)`

to override the default `resources` prefix and assign a specific prefix for a package.


### Extending the Meta Module

There is a `MetaModuleExtension` extension that allows other Crnk modules contribute `MetaProvider`
implementation. This allows to:

- add `MetaFilter` implementations to intercept and modify meta elements upon initialization and request.
- add `MetaPartition` implementations to introduce new, isolated areas in the meta model, like a JPA
  meta model next to the JSON API one (like for documentation purposes).

For more detailed information have a look at the current `ResourceMetaProvider`.




## Activiti Module

NOTE: This module is in new and in incubation. Feedback and improvements welcomed.

There is an `ActivitiModule` for the https://www.activiti.org[Activiti] workflow engine that offers an alternative REST API.
The motivation of `ActivitiModule` is to:

- have a JSON API compliant REST API to benefit from the resource-oriented architecture, linking, sorting, filtering, paging,
  and client-side tooling of JSON API.
- have a type-safe, non-generic REST API that is tailored towards the use cases at hand. This means that for each process
  and task definition, there is a dedicated repository and resource type for it. The resource is comprised of
  both the static fields provided by Activiti (like `name`, `startTime` and `priority`) and the dynamic fields
  stored by the application as process/task/form variables. Mapping to static resp. dynamic fields is done
  automatically by the `ActivitiModule` and hidden from consumers. The repository implementations ensure a proper isolation of different types. And
  the application is enabled, for example, to introduce custom security policies for each resource with
  the `SecurityModule` or a `ResourceFilter`.

This setup differs substantially from the API provided by Activiti that is implemented
in generic fashion.

### Setup

The `ActivitiModule` comes within a small example application within the `src/main/test` directory that showcases its use.
It sets up an approval flow where changes to the `Schedule` resource must be approved by a user.

The `ActivitiModule` implements four resource base classes that match the equivalent Activiti classes:

- `ExecutionResource`
- `FormResource`
- `ProcessInstanceResource`
- `TaskResource`

To setup a JSON API repository for a process or task, the corresponding resource class can be subclassed and extended with
the application specific fields. For example:

[source]
.ApprovalProcessInstance.java
----
include::../../../../crnk-activiti/src/test/java/io/crnk/activiti/example/approval/ApprovalProcessInstance.java[tag=docs1]
	...
include::../../../../crnk-activiti/src/test/java/io/crnk/activiti/example/approval/ApprovalProcessInstance.java[tag=docs2]
----

and

[source]
.ScheduleApprovalProcessInstance.java
----
include::../../../../crnk-activiti/src/test/java/io/crnk/activiti/example/model/ScheduleApprovalProcessInstance.java[tag=docs1]
	...
include::../../../../crnk-activiti/src/test/java/io/crnk/activiti/example/model/ScheduleApprovalProcessInstance.java[tag=docs2]
----

The example application makes use of an intermediate `ApprovalProcessInstance` base class to potentially share the approval
logic among multiple entities in the future (if it would be real-world use case). `ScheduleApprovalProcessInstance` has
the static fields of Activiti and a number of custom, dynamic fields like `resourceType`, `resourceId` and `newValues`.
The dynamic fields will be mapped to to process, task resp. form variables.

Notice the relation to `ApproveTask`, which is a task counter part extending from `TaskResource`. If a process has multiple
tasks, you may introduce multiple such relationships.

Finally, the setup of the `ActiviModule` looks like:

[source]
.ApprovalTestApplication.java
----
include::../../../../crnk-activiti/src/test/java/io/crnk/activiti/example/ApprovalTestApplication.java[tag=activitiModule]
----

- `ActivitiModuleConfig` allows to register processes and tasks that then will be exposed as repositories.
- `ScheduleApprovalProcessInstance`, `ApproveTask` and the `approveTask` relationship are registered.
- `ApproveTask` is user task that is handled by submitting an `ApproveForm`.
- `filterByProcessDefinitionKey` and `filterByTaskDefinitionKey` ensure that the two repositories
  are isolated from other repositories for `GET`, `POST`, `PATCH` and `DELETE` operations.

One could imagine to make this configuration also available through an annotation-based API in the future as it is
closely related to the resource classes and fields.


### Example application

The example application goes a few steps further in the setup. The patterns of those steps might be of
interest of consumers of the `ActivitiModule` as well.

The workflow looks as follows:

[source]
.approval.bpmn20.xml
----
include::../../../../crnk-activiti/src/test/resources/approval.bpmn20.xml[]
----

There is a:

- `approveScheduleTask` task requires a form submission by a user.
- `approvalExclusiveGateway` checks whether the change was accepted.
- `scheduleChangeApproved` invokes `${approvalManager.approved(execution)}` whereas `approvalManager` is a Java object
  taking care of the approval handling and registered to `activiti.cfg.xml`.
- `approvalManager.approved(...)` reconstructs the original request and forwards it to Crnk again to save the approved
  changes. This means the regular `ScheduleRepository` implementation will be called in the same fashion as for
   a typical request. Real world use cases may also need to save and reconstruct the security context.

For the approval-related functionality a second module is registered:

[source]
.ApprovalTestApplication.java
----
include::../../../../crnk-activiti/src/test/java/io/crnk/activiti/example/ApprovalTestApplication.java[tag=approvalModule]
----

- `ApprovalRepositoryDecorator` hooks into the request processing of the Crnk engine and intercepts
 all `PATCH` and `POST` requests for the `Schedule` resource. The decorator then may chooses to
 abort the request and start an approval flow instead with the help of `ApprovalManager`.
- `ApprovalRelationshipRepository` introduces an additional relationship between the actual resources
  and approval resources. It can be used, for example, by user interfaces to show the current status
  of an open approval workflow. `ApprovalRelationshipRepository.getResourceFields` declares
  the relationship field, meaning that the original application resource does not have to declare the
  relationship. This may or may not be useful depending on how much control there is over the original resource
  (for example there is no control over JPA entities).
- `historic(...)` method specify the historic resource counterparts to query the history.

The chosen setup leads to an approval system that is *fully transparent* to the actual repository implementations
and can be added to any kind of repository.

`ApprovalIntTest` showcases the example workflow by doing a change,
starting the approval process, submitting a form and then verifying the changes have been saved.


### Limitations

- Currently the main entities of Activiti have been exposed. Configuration-related repositories
  could be exposed as well in the future.
- Historic repositories are still considered being experimental.
- Activiti has a limited query API that is inherited by the application. Potentially `crnk-jpa` could help
  out a bit in this area.
- Multi-tenancy is not yet done out-of-the-box.
- Activiti has been forked to Flowable. As of yet it is unclear whether one or both project
  will survive in the long-term.




