anchor:generation[]

# Generation

NOTE: this feature is still in incurbation, feedback and contributions welcomed. In particular further frameworks like
Spring must be supported.

Crnk allows the generation of Typescript stubs for type-safe, client-side web development. Contributions for other
languages like iOS would be very welcomed.

## Typescript

NOTE: Available soon (ngrx-json-api needs to be released as well)

The Typescript generator allows the generation of:

- interfaces for resources and related objects (like nested objects and enumeration types).
- interfaces for result documents (i.e. resources and any linking and meta information).
- interfaces for links information.
- interfaces for meta information.
- method to create an empty object instance.

Currently the generator targets the <a href="https://github.com/abdulhaq-e/ngrx-json-api">ngrx-json-api</a> library.
Support for other libraries/formats would be straightforward to add, contributions welcomed. A generated resource looks
like:

[source]
----
include::../../../../crnk-gen-typescript/src/test/resources/expected_schedule_without_expressions.ts[]
----

Internally the generator has to make use of the running application to gather the necessary information for generation. This
approach not only supports the regular resources and repositories manually implemented by the application,
but also more advanced patterns like resources obtained through third-party modules or derived from JPA entities. To get the
application to a running state at built-time, the generator makes use of the JUnit setup of the application.
So far supported are a setup of JUnit with Deltaspike for JEE application. Other non-CDI integrations like Spring to follow soon.

A setup may look like:

[source]
----
buildscript {
	dependencies {
		classpath "io.crnk:crnk-gen-typescript:${version}"
		classpath "com.moowork.gradle:gradle-node-plugin:1.1.1"
	}
}

node {
	version = '6.9.1'
	download = true
	distBaseUrl = "${ADN_NODEJS_MIRROR_BASE_URL}/dist"
}

apply plugin: 'crnk-gen-typescript'

configurations {
	typescriptGenRuntime
}

dependencies {
	typescriptGenRuntime project(':project-to-generate-from')
}

typescriptGen{

	runtime {
		configuration = 'typescriptGenRuntime'
	}

	npm {
		packageVersion = '0.0.1'
		packageName = '@adnovum/moap-movie-management-api'
		description = 'movie management API to access backend'
		gitRepository = 'https://.../bitbucket/scm/moap/moap-movie.git'
		license = 'MIT'
		// packagingEnabled = false
		// outputDir = ...
	}

	includes = ['ch.adnovum.moap.movie.somePackage']
	excludes = ['ch.adnovum.moap.movie.somePackage.otherPackage']

	packageMapping['ch.adnovum.moap.movie.management'] = '@adnovum/moap-movie-management-api'
	peerDependencies['ngrx-json-api'] = '>=1.2.0'

	// genDir = ...

}
typescriptGen.init()


----

- the `moowork` plugin is used to to gain a `node` setup.
- `packageName`, `description`, `license`, `gitRepository` are added to the generated `package.json`.
- by default the package version matches the npm version.
- a mapping of Java package name (resp. `MetaElement.id`) to npm packages must be specified.
  Only resources are generated whose package matches the chosen `npm.packageName`.
  All other resources are imported as external NPM dependency.
- `includes` and `excludes` allow to include and exclude packages from generation.
- crnk-meta is used to gather a meta model of the underlying resources (or a any other type of object like JPA entities).
  Important to know is that every object is assigned a string-based meta id. For typical, simpler use cases this matches
  the package resp. class name. But for more advanced use cases those may differ.
- applying `crnk-gen-typescript` results in a new `assembleTypescript` task. It and its dependencies
  generate, compile and package the Typescript sources. We chose not to add a dependency from `assembleTypescript` to
  `assemble` has a backend-only
  develop may not need to run with every `assemble` run. Typically `assembleTypescript` is either hooked
  into the publishing or added as dependency on a frontend project contained within the same Gradle project.
- `runtime.configuration` sets the Gradle configuration to use to obtain a classpath. In the given example
   `typescriptGenRuntime` is used. You may also use `compile` or anything else.
- `packagingEnabled` enabled is enabled by default and leads to the generation of a `package.json` and `tsconfig.json` file.
  With this a fully functional NPM package is generated. This is typically used when a backend application wants to
  publish its stubs to an NPM repository. Setting it to false will result in the generation of the
  Typescript files only. This is typically used when the files are directly generated into a frontend project.
- `genDir` allows to update where the source files are generated to.
- `npm.outputDirectory` allows to specify where the compiled NPM package should be placed.


NOTE: the generator plugin is not yet included in any example applications. It is not possible to
include a plugin from within the same project. At some point an external example application will be
setup to showcase the use of the plugin.

