anchor:generation[]

# Generation

Crnk allows the generation of Typescript stubs for type-safe, client-side web development. Contributions for other
languages like iOS would be very welcomed.

## Typescript

The Typescript generator allows the generation of:

- interfaces for resources and related objects (like nested objects and enumeration types).
- interfaces for result documents (i.e. resources and any linking and meta information).
- interfaces for links information.
- interfaces for meta information.
- methods to create empty object instances.
- QueryDSL-like expression classes (see <expressions>)

Currently the generator targets the http://github.com/abdulhaq-e/ngrx-json-api[ngrx-json-api] library.
Support for other libraries/formats would be straightforward to add, contributions welcomed. A generated resource looks
like:

[source]
----
include::../../../../crnk-gen-typescript/src/test/resources/expected_schedule_without_expressions.ts[]
----

Internally the generator has to make use of the running application to gather the necessary information for generation. This
approach not only supports the typical, manual implement resources and repositories manually, but also
the ones obtained through third-party modules such the JPA entities exposed by the JPA module. There are different
possibilities to do that. https://github.com/crnk-project/crnk-framework/blob/master/crnk-client-angular-ngrx/build
.gradle[crnk-client-angular-ngrx]
does such a setup manually in Gradle. Alternatively, there is a Gradle plugin taking care of the generator setup. It makes use
of the JUnit to get
the application to a running state at built-time. Currently supported are CDI and Spring-based applications.
Such a setup may look like:

[source]
----
buildscript {
	dependencies {
		classpath "io.crnk:crnk-gen-typescript:${version}"
		classpath "com.moowork.gradle:gradle-node-plugin:1.1.1"
	}
}

node {
	version = '6.9.1'
	download = true
	distBaseUrl = "${ADN_NODEJS_MIRROR_BASE_URL}/dist"
}

apply plugin: 'crnk-gen-typescript'

configurations {
	typescriptGenRuntime
}

dependencies {
	typescriptGenRuntime project(':project-to-generate-from')
}

typescriptGen{

	runtime {
		configuration = 'typescriptGenRuntime'
        spring {
        	profile = 'test'
        	configuration = 'ch.adnovum.arch.demo.management.service.ManagementApplication'
        }
	}

	npm {
		packageVersion = '0.0.1'
		packageName = '@crnk/example-api'
		description = 'example API to access example backend'
		gitRepository = 'https://.../bitbucket/scm/crnk/example.git'
		license = 'MIT'
		// packagingEnabled = false
		// outputDir = ...
	}

	includes = ['resources.task']
	excludes = ['resources.project']

	forked = true

	packageMapping['resources.something'] = '@crnk/some-demo-library'
	peerDependencies['ngrx-json-api'] = '>=2.0.0-beta.6'
	generateExpressions = true

	// genDir = ...

}
typescriptGen.init()


----

- the `moowork` plugin is used to to gain a `node` setup.
- `packageName`, `description`, `license`, `gitRepository` are added to the generated `package.json`.
- by default the package version matches the npm version.
- `crnk-meta` is used to gather a meta model of the underlying resources (or a any other type of object like JPA entities).
  Important to know is that every object is assigned a string-based meta id. By default the
  meta id matches `resources.<resourceType>`. For example a Task resource with resource type `task` has a
  `resources.task` meta id.
- applying `crnk-gen-typescript` results in a new `assembleTypescript` task. Consumers may want to add
  that task to `assemble` as dependency.
- `runtime.configuration` sets the Gradle configuration to use to obtain a classpath. In the given example
   `typescriptGenRuntime` is used. You may also use `compile` or anything else.
- `runtime.spring` is used to configure the Spring profile and configuration class to use to setup the spring application.
  For CDI application is can be omitted.
- `packagingEnabled`  triggers the generation of a `package.json` and `tsconfig.json` file (`true` as default).
  Useful to publish the stubs to an NPM repository for use by other projects.
  Setting it to false will result in the generation of the Typescript files only. This may be used to generate
   files directly into an existing frontend project. In this case only the `generateTypescript` task is available, there
   is no assembly taking place.
- `genDir` specifies where source files are generated to.
- `npm.outputDirectory` specifies where the compiled NPM package should be placed (`build/npm` as default).
- `generateExpressions` specifies whether QueryDSL like classes should be generated (`false` as default).
- `packageMapping` allows to specify into which libraries resources belong to. By default all resources have
  a `resources.` meta id prefix and go into the currently generated package. In the example above, all resources with a
  `something/*` resource type resp. `resources.something` meta id prefix are included from a `@crnk/some-demo-library`
  library and no longer get generated manually.
- `includes` and `excludes` allow to include and exclude resources from generation based on their meta id.
- by default the generation takes place in a forked process. Since the generator typically
  runs the application and that may not properly cleanup, it is recommended to let the
  generator fork a new process to avoid resource leakage in Gradle daemons and
  have more stable builds.

NOTE: the generator plugin is not yet included in any example applications. It is not possible to
include a plugin from within the same project. At some point an external example application will be
setup to showcase the use of the plugin.

