anchor:generation[]

# Generation

Crnk allows the generation of:

- Typescript stubs for type-safe, client-side web development.
- Type-safe `QuerySpec` and `PathSpec` types.

Contributions for other languages like iOS would be very welcomed.

anchor:generation_java[]

## Java Annotation Processor

WARNING: This annotation processor is still experimental. Feedback welcomed.

`crnk-gen-java` provides an annotation processor to generate a type-safe API for the construction of `QuerySpec`
and `PathSpec` objects. The annotation processor is setup like any other annotation processor.
In Gradle it looks like:

[source]
----
dependencies{
  annotationProcessor 'io.crnk:crnk-gen-java'
  ...
}
----

One may also has enable annotation processors in the IDE (most notable in IntelliJ IDEA). One can then make use of it like:

[source,Java]
----
include::../../../../crnk-gen/crnk-gen-java/src/test/resources/TypedQuerySpecTest.java[]
----

More improvements to the generates types are thinkable in the future, such as limiting
the set of fields depending on the use case (inclusions, field sets, sorting, filtering) depending on the
capability of that particular field. Contributions welcomed.

## Typescript

The Typescript generator allows the generation of:

- interfaces for resources and related objects (like nested objects and enumeration types).
- interfaces for result documents (i.e. resources and any linking and meta information).
- interfaces for links information.
- interfaces for meta information.
- methods to create empty object instances.

It can generate either plain Typescript interfaces or
target http://github.com/abdulhaq-e/ngrx-json-api[ngrx-json-api].
Support for other libraries/formats would be straightforward to add, contributions welcomed. A generated resource looks
like in <<format_plain,plain-text format>>:

[source]
----
include::../../../../crnk-gen/crnk-gen-typescript/src/test/resources/expected_schedule_plain_json.ts[]
----

and for http://github.com/abdulhaq-e/ngrx-json-api[ngrx-json-api]:

[source]
----
include::../../../../crnk-gen/crnk-gen-typescript/src/test/resources/expected_schedule_without_expressions.ts[]
----

For an example have a look at the Crnk example application, see https://github.com/crnk-project/crnk-example[crnk-project/crnk-example].

There is a Gradle plugin to run Typescript (and other) generation. The setup looks like:

[source]
----
buildscript {
	dependencies {
		classpath "io.crnk:crnk-gen-gradle:${version}"
	}
}

apply plugin: 'crnk-gen'
crnkGen {
    runtime {
        configuration = 'typescriptGenRuntime'
    }

    // fork generation into new process to have clean environment
    forked = true

    // specify the package to look for resources
    resourcePackages = ['io.crnk.test']

    typescript {
        // enable Typescript generation within Gradle plugin
        enabled = true

        // specify output format
        format = 'PLAINJSON' // or 'JSONAPI'

        // specify location of generated sources
        genDir = file('src/resources')
    }
}
crnkGen.init()
----

Applying `crnk-gen` results in a new `generateTypescript` task to perform the generation.

////
The plugin strives for the generated sources to closely resemble the REST layer.
As a consequence it makes use of the resource types and json names rather than Java names for the generated sources.
Important to know is that each type is assigned a meta id: for resources it is `resources.<resourceType>` and
for all other objects the Java package name. Based on the meta id, there are a number of possibilities to influence
the generation:

- `includes` and `excludes` allow to include and exclude resources from generation based on their meta id.
- `directoryMapping` allows to specify into which (sub)directory types are generated into. By default
   will be generated into the root directory.
- `packageMapping` allows to specify that a given type is obtained from a third-party library.
////


## Gradle customizations

Internally the Crnk Gradle plugin supports multiple ways of looking up the set of available resources and repositories
to generate.
The simplest way is by scanning the classpath for @JsonApiResource-annotated classes. More elaborate setups
can also launch an application (e.g. with Spring or CDI) and extract the information from the running application.
While the former is simpler to setup, the later can deal with all border cases like a repository being backed
by something different than a @JsonApiResource-annotated class. For Spring this looks like:

[source]
----
crnkGen{

    // launch a Spring application to extract information about available resources
	runtime {
		configuration = 'typescriptGenRuntime'
        spring {
        	profile = 'test'
        	configuration = 'io.crnk.example.ExampleApplication'
        	initializerMethod = 'someInitMethod' // optional
        	defaultProperties['someKey'] = 'someValue'
        }
	}

	...
}
crnkGen.init()
----

Typically a test profile is used to bring the Spring application up in order to then extract the repositories for generation.
