anchor:generation[]

# Generation

Crnk allows the generation of:

- Typescript stubs for type-safe, client-side web development.
- Type-safe `QuerySpec` and `PathSpec` types.

Contributions for other languages like iOS would be very welcomed.

anchor:generation_java[]

## Java Annotation Processor

WARNING: This annotation processor is still experimental. Feedback welcomed.

`crnk-gen-java` provides an annotation processor to generate a type-safe API for the construction of `QuerySpec`
and `PathSpec` objects. The annotation processor is setup like any other annotation processor.
In Gradle it looks like:

[source]
----
dependencies{
  annotationProcessor 'io.crnk:crnk-gen-java'
  ...
}
----

One may also has enable annotation processors in the IDE (most notable in IntelliJ IDEA). One can then make use of it like:

[source,Java]
----
include::../../../../crnk-gen/crnk-gen-java/src/test/resources/TypedQuerySpecTest.java[]
----

More improvements to the generates types are thinkable in the future, such as limiting
the set of fields depending on the use case (inclusions, field sets, sorting, filtering) depending on the
capability of that particular field. Contributions welcomed.

## OpenAPI

WARNING: This generator is still experimental. Feedback welcomed.

`crnk-gen-openapi` provides a way to generate OpenAPI files. The OpenAPI Specification,
originally known as the Swagger Specification, is a specification for machine-readable interface
files for describing, producing, consuming, and visualizing RESTful web services.

The OpenAPI generator allows the generation of:

- specifications of paths for resources and related objects (like nested objects and enumeration types).
- specifications of result documents (i.e. resources and any linking and meta information).
- specifications of links information.
- specifications of meta information.
- specifications of standard errors
- specifications of standard parameters

If a `templateName` file is provided, it will override the `projectName`, `projectVersion`, and
`projectDescription` passed into the generate step. Similarly, descriptions of operations can be
overridden within the provided OpenAPI template file.

There is a Gradle plugin to run OpenAPI (and other) generation. The setup looks like:

[source]
----
buildscript {
	dependencies {
		classpath "io.crnk:crnk-gen-gradle:${version}"
	}
}

apply plugin: 'crnk-gen'
crnkGen {
    runtime {
        // Gradle classpath configuration to use
        configuration = 'runtime'
    }

    // fork generation into new process to have clean environment
    forked = true

    // specify the package to look for resources
    resourcePackages = ['io.crnk.test']

    openapi {
        // enable OpenAPI generation within Gradle plugin
        enabled = true

				// specify name of openapi template in the build dir to merge onto
				templateName = "openapi-template.yml"

				// specify name of API to display in the generated OpenAPI file
				projectName = "Generated Title"

				// specify version of the API to display in the generated OpenAPI file
				projectVersion = "0.1.0"

				// specify name of openapi template in the build dir to merge onto
				projectDescription = "A generated description of the API."

        // specify location of generated sources
        genDir = file('src/resources')
    }
}
crnkGen.init()
----

Applying `crnk-gen` results in a new `generateOpenapi` task to perform the generation.

## Typescript

The Typescript generator allows the generation of:

- interfaces for resources and related objects (like nested objects and enumeration types).
- interfaces for result documents (i.e. resources and any linking and meta information).
- interfaces for links information.
- interfaces for meta information.
- methods to create empty object instances.

It can generate either plain Typescript interfaces or
target http://github.com/abdulhaq-e/ngrx-json-api[ngrx-json-api].
Support for other libraries/formats would be straightforward to add, contributions welcomed. A generated resource looks
like in <<format_plain,plain-text format>>:

[source]
----
include::../../../../crnk-gen/crnk-gen-typescript/src/test/resources/expected_schedule_plain_json.ts[]
----

and for http://github.com/abdulhaq-e/ngrx-json-api[ngrx-json-api]:

[source]
----
include::../../../../crnk-gen/crnk-gen-typescript/src/test/resources/expected_schedule_without_expressions.ts[]
----

For an example have a look at the Crnk example application, see https://github.com/crnk-project/crnk-example[crnk-project/crnk-example].

There is a Gradle plugin to run Typescript (and other) generation. The setup looks like:

[source]
----
buildscript {
	dependencies {
		classpath "io.crnk:crnk-gen-gradle:${version}"
	}
}

apply plugin: 'crnk-gen'
crnkGen {
    runtime {
        // Gradle classpath configuration to use
        configuration = 'runtime'
    }

    // fork generation into new process to have clean environment
    forked = true

    // specify the package to look for resources
    resourcePackages = ['io.crnk.test']

    typescript {
        // enable Typescript generation within Gradle plugin
        enabled = true

        // specify output format
        format = 'PLAINJSON' // or 'NGRX'

        // specify location of generated sources
        genDir = file('src/resources')
    }
}
crnkGen.init()
----

Applying `crnk-gen` results in a new `generateTypescript` task to perform the generation.

////
The plugin strives for the generated sources to closely resemble the REST layer.
As a consequence it makes use of the resource types and json names rather than Java names for the generated sources.
Important to know is that each type is assigned a meta id: for resources it is `resources.<resourceType>` and
for all other objects the Java package name. Based on the meta id, there are a number of possibilities to influence
the generation:

- `includes` and `excludes` allow to include and exclude resources from generation based on their meta id.
- `directoryMapping` allows to specify into which (sub)directory types are generated into. By default
   will be generated into the root directory.
- `packageMapping` allows to specify that a given type is obtained from a third-party library.
////


## Gradle customizations


Internally the Crnk Gradle plugin supports multiple ways of looking up the set of available resources and repositories
to generate. The simplest way is by scanning the classpath for `@JsonApiResource`-annotated classes.
The classpath for scanning can be set through the use of a regular Gradle configuration object, for example:

[source]
----
crnkGen{
	runtime {
		configuration = 'runtime'
	}

	...
}
crnkGen.init()
----

More elaborate setups can also launch an application (e.g. with Spring or CDI) and extract the information
from the running application. While the former is simpler to setup, the later can deal with all border cases
like a repository being backed by something different than a `@JsonApiResource`-annotated class. Such a
Spring setup looks like:

[source]
----
crnkGen{

    // launch a Spring application to extract information about available resources
	runtime {
		configuration = 'runtime'
        spring {
        	profile = 'test'
        	configuration = 'io.crnk.example.ExampleApplication'
        	initializerMethod = 'someInitMethod' // optional
        	defaultProperties['someKey'] = 'someValue'
        }
	}

	...
}
crnkGen.init()
----

Typically a test profile can used to bring the Spring application up as unit tests are supposed to be
self-contained and allow the application to boot up. The repositories are then retrieved from the
Spring dependency injection container.




## Documentation with AsciiDoc

WARNING: This is still experimental. Feedback welcomed.

Documentation of REST APIs has a long history of various tooling. Swagger/OpenAPI there is the classical choice,
but comes with a variety of disadvantages:

- Mechanisms used to extract information from an implementation often fail understand the full scope of it.
- Annotations for descriptions lead to a large amount of boiler-plate.
- Swagger UI is delivered as webapp and hard to enrich with custom information.

This triggered, for example, the development of https://github.com/Swagger2Markup/swagger2markup[swagger2markup] to
make is of AsciiDoc as output target. This in turn lets developers manually written and generated
documentation and publish it as HTML and PDF in a potentially versioned manner.

Further progress iad made by https://docs.spring.io/spring-restdocs/docs/1.2.6.RELEASE/reference/html5/[spring-restdocs].
Instead of attempting to write a specification, request and responses are captured from unit tests and
enriched with documentation to then save as AsciiDoc.  This ensures 100% accurate documentation at all time since.

JSON:API enables developers to take a further leap. Since it provides a well-defined standard for many aspects
of a REST endpoint, such as parameter handling, status codes and linking, it greatly simplifies the documentation task.
Many things are covered by the standard and the documentation can focus on the essential aspects of the
application. This in turn is realized by the AsciiDoc module of the Crnk generator.

The setup looks like:

[source]
----
crnkGen{
    runtime {
        configuration = 'typescriptGenRuntime'
    }

    // specify the package to look for resources
    resourcePackages = ['io.crnk.test']

    asciidoc {
        // enable Typescript generation within Gradle plugin
        enabled = true

        // title of generated document
        title = "Api Documentation"

        // specify location of generated sources
        genDir = file('build/generated/sources/asciidoc')
    }
}
crnkGen.init()
----

This results in a `generateAsciidoc` task to perform the generation.  The output directory then
contains a collection of files that can either be included individually or together with the main `index.adoc`.

Descriptions for resources and fields are extracted from JavaDoc.

The generated documentation can be enriched with request/response examples from unit tests. An example looks like:

[source]
----
include::../../../../crnk-gen/crnk-gen-asciidoc/src/test/java/io/crnk/gen/asciidoc/AsciiDocCaptureTest.java[]
----

The example sets up a Crnk client and server. They are directly connected through `InMemoryHttpAdapter` to
by-pass the HTTP layer and forgo the setup of a web server. The `AsciidocCaptureModule` is add to the
client to do the capturing. To then capture a request:

[source]
----
asciidoc.capture("Create new Task").call(() -> repository.create(newTask));
----

If the output is matched with Crnk generator plugin, then the captured test cases will be picked up automatically.
A full setup is available in the main https://github.com/crnk-project/crnk-example[crnk-example] application.




