anchor:generation[]

# Generation

Crnk allows the generation of Typescript stubs for type-safe, client-side web development. Contributions for other
languages like iOS would be very welcomed.

## Typescript

The Typescript generator allows the generation of:

- interfaces for resources and related objects (like nested objects and enumeration types).
- interfaces for result documents (i.e. resources and any linking and meta information).
- interfaces for links information.
- interfaces for meta information.
- methods to create empty object instances.
- QueryDSL-like expression classes (see <expressions>)

Currently the generator targets the http://github.com/abdulhaq-e/ngrx-json-api[ngrx-json-api] library.
Support for other libraries/formats would be straightforward to add, contributions welcomed. A generated resource looks
like:

[source]
----
include::../../../../crnk-gen-typescript/src/test/resources/expected_schedule_without_expressions.ts[]
----

For an example have a look at the Crnk example application, see https://github.com/crnk-project/crnk-example[crnk-project/crnk-example].


### Setup

Internally the generator supports multiple ways of looking up the set of available resources and repositories
to generate.
The simplest way is by scanning the classpath for @JsonApiResource-annotated classes. More elaborate setups
can also launch an application (e.g. with Spring or CDI) and extract the information from the running application.
While the former is simpler to setup, the later can deal with all border cases like a repository being backed
by something different than a @JsonApiResource-annotated class.

The configuration looks like:


[source]
----
buildscript {
	dependencies {
		classpath "io.crnk:crnk-gen-typescript:${version}"
		classpath "com.moowork.gradle:gradle-node-plugin:1.1.1"
	}
}

node {
	version = '6.9.1'
	download = true
}

apply plugin: 'crnk-gen-typescript'

configurations {
	typescriptGenRuntime
}

dependencies {
	typescriptGenRuntime project(':project-to-generate-from')
}

typescriptGen{

    // scan for resources on the classpath
    resourcePackages = ['io.crnk.example']

    // launch a Spring application to extract information about available resources
	// runtime {
	//	configuration = 'typescriptGenRuntime'
    //    spring {
    //    	profile = 'test'
    //    	configuration = 'io.crnk.example.ExampleApplication'
    //    	initializerMethod = 'someInitMethod' // optional
    //    	defaultProperties['someKey'] = 'someValue'
    //    }
	// }

	npm {
		// map given Java package to a subdirectory of genDir
		directoryMapping['io.myapp.types'] = '/types'

		// map a given package to a third-party library
		packageMapping['io.other.app'] = '@other/app'
	}

	// include/exclude elements from generation
	includes = ['resources.task']
	excludes = ['resources.project']

	// fork generation into new process to have clean environment
	forked = true

	// generate QueryDSL-like expression objects
	generateExpressions = true

	// specify location of generated sources
	genDir = ...

}
typescriptGen.init()
----

An example is given in https://github.com/crnk-project/crnk-example/blob/master/crnk-example-frontend/build.gradle[crnk-example].

Applying `crnk-gen-typescript` results in a new `generateTypescript` task. Consumers may want to add
that task to `assemble` as dependency. The sources are then generated to `genDir` as specified.

`resourcePackages` specifies the package to scan for resources. Alternatively and commented out, it is shown
how to launch a Spring application to extract the resource information. Typically by running the application
with a test profile. CDI works equally well if Weld is found on the classpath (such as with Deltaspike).

The plugin strives for the generated sources to closely resemble the REST layer.
As a consequence it makes use of the resource types and json names rather than Java names for the generated sources.
Important to know is that each type is assigned a meta id: for resources it is `resources.<resourceType>` and
for all other objects the Java package name. Based on the meta id, there are a number of possibilities to influence
the generation:

- `includes` and `excludes` allow to include and exclude resources from generation based on their meta id.
- `directoryMapping` allows to specify into which (sub)directory types are generated into. By default
   will be generated into the root directory.
- `packageMapping` allows to specify that a given type is obtained from a third-party library.

The plugin allows various further customization options:

- `generateExpressions` specifies whether QueryDSL like classes should be generated (`false` as default).
- by default the generation takes place in a forked process. Since the generator typically
  runs the application and that may not properly cleanup, it is recommended to let the
  generator fork a new process to avoid resource leakage in Gradle daemons and
  have more stable builds.


### Error Handling

Since the Typescript generator internally launches the application to extract information about its resources, the
generator is in need of a consistent application/Crnk setup. For example, every resource must have a match
repository serving it. Otherwise
inconsistencies can arise that will break the generation. This means if the generation fails, it is usually
best to verify the the application itself is working properly.

To track errors further down, a log file is written to `build/tmp/crnk.gen.typescript.log`. It runs with
`io.crnk` on level `DEBUG` to output a large number of information.
