:sectnums:

# Crnk Documentation
:toc: left
:toclevels: 3


Crnk is an implementation of the JSON API specification and recommendations in Java. It allows you to rapidly
build REST APIs without having to worry about lower protocol details and lets you instead
focus on your application. JSON API and Crnk come with support for:

- client and server implementation (with a focus on the later).
- standardized url handling such as `/api/persons?filter[title]=John` and `/api/persons/{id}`
- sorting, filtering, paging of resources
- attaching link and meta information to data.
- inserting, updating and deleting of resources.
- support to request complex object graphs in a single request with JSON API inclusions.
- support for partial objects with sparse field sets.
- atomically create, update and delete multiple with http://jsonpatch.com/[jsonpatch.com].
- a flexible module API to choose and extend the feature set of Crnk.
- eased testing with the client implementation providing type-safe stubs to access server repositories.
- repositories providing runtime/meta information about Crnk to implement, for example, documentation
  and UI automation.
- generation of type-safe client stubs (currently Typescript as target language implemented)

Next to that Crnk supports many popular frameworks and APIs:

- CDI: resolve repositories and extensions with CDI.
- Spring: run Crnk with Spring, including support for Spring Boot, Spring ORM and Spring Security.
- Servlet API: run Crnk as servlet.
- JAXRS: run Crnk as feature.
- JPA: expose entities as JSON API resources.
- bean validation: properly marshal validation and constraints exceptions.
- Zipkin: trace all your calls.

:leveloffset: 1

include::architecture.adoc[]
include::setup.adoc[]
include::resource.adoc[]
include::repositories.adoc[]
include::client.adoc[]
include::modules.adoc[]
include::module_development.adoc[]
include::generation.adoc[]
include::angular.adoc[]
include::faq.adoc[]

:leveloffset: 0