:sectnums:

# Crnk Documentation
:toc: left
:toclevels: 3


Crnk is a native resource-oriented rest library where resources and their relationship take the center stage. With this
inner workings of Crnk differ quite dramatically from most REST library out there. Usually, resources and
relationships are not more than just path mappings specified by class and method annotations. This fact opens up powerful new
possibilities.

Crnk follows the JSON API specification and recommendations. It allows you to rapidly
build REST APIs without having to worry about lower protocol details and lets you instead
focus on what matters: your application. JSON API and Crnk come with support for:

- client and server implementation (with a focus on the later).
- standardized url handling such as `/api/persons?filter[title]=John` and `/api/persons/{id}`
- sorting, filtering, paging of resources
- attaching link and meta information to data.
- inserting, updating and deleting of resources.
- support to request complex object graphs in a single request with JSON API inclusions.
- support for partial objects with sparse field sets.
- atomically create, update and delete multiple with http://jsonpatch.com/[jsonpatch.com].
- a flexible module API to choose and extend the feature set of Crnk.
- eased testing with the client implementation providing type-safe stubs to access server repositories.
- repositories providing runtime/meta information about Crnk to implement, for example, documentation
  and UI automation.
- generation of type-safe client stubs (currently Typescript as target language implemented)
- binding of Angular components with https://github.com/abdulhaq-e/ngrx-json-api[ngrx-json-api] to Crnk endpoints.

Crnk is small, modular and lightweight. It integrates well with many popular frameworks and APIs:

- CDI: resolve repositories and extensions with CDI.
- Spring: run Crnk with Spring, including support for Spring Boot, ORM, Security and Sleuth.
- Servlet API: run Crnk as servlet.
- JAXRS: run Crnk as feature.
- JPA: expose entities as JSON API resources.
- bean validation: properly marshal validation and constraints exceptions.
- Zipkin: trace all your calls.

While Crnk follows the JSON API specification, it is not limited to that. Have a look at the
http://www.crnk.io/[roadmap> for more information.


:leveloffset: 1

include::examples.adoc[]
include::architecture.adoc[]
include::setup.adoc[]
include::resource.adoc[]
include::repositories.adoc[]
include::client.adoc[]
include::modules.adoc[]
include::module_development.adoc[]
include::generation.adoc[]
include::angular.adoc[]
include::faq.adoc[]

:leveloffset: 0