
anchor:moduledev[]

# Advanced Customizations through Modules

Crnk has a module API that allows to extend the core functionality by third-party contributions.
The mentioned JPA module in the next section is an example for that. The API is similar in spirit
to the one of the `https://github.com/FasterXML/jackson`. The main interface is `Module` with
a default implementation provided by `SimpleModule`. A module has access to a `ModuleContext`
that allows to register all kinds of extensions like new `ResourceInformationBuilder`,
`ResourceLookup`, `Filter`, `ExceptionMapper` and Jackson modules. It also gives access to the
`ResourceRegistry` holding information about all the repositories registered to crnk.
The `JpaModule` in `crnk-data-jpa` provides a good, more advanced example of using the
module API.


anchor:requestfilter[]

## Request Filtering

Crnk provides three different, complementing mechanisms to hook into the request processing.

The `DocumentFilter` interface allows to intercept incoming requests and do
any kind of validation, changes, monitoring, transaction handling, etc. `DocumentFilter` can be
hooked into Crnk by setting up a module and registering the filter to the
`ModuleContext`. Not that for every request, this interface is called exactly once.

A request may span multiple repository accesses. To intercept the actual repository requests,
implement the `RepositoryFilter` interface. `RepositoryFilter` has a number of methods
that allow two intercept the repository request at different stages. Like `Filter` it can be
hooked into Crnk by setting up a module and registering the filter to the
`ModuleContext`.

Similar to `RepositoryFilter` it is possible to decorate a repository with another repository
implementing the same Crnk repository interfaces. The decorated repository instead of
the actual repository will get called and it is up to the decorated repository of how to proceed
with the request, usually by calling the actual repository. `RepositoryDecoratorFactory`
can be registered with `ModuleContext.addRepositoryDecoratorFactory`. The factory gets
notified about every repository registration and is then free do decorate it or not.


anchor:modificationfilter[]

## Filter Modifications

Changes to attributes and relationships can be tracked by implementing
`ResourceModificationFilter`. The filter is invoked upon an incoming request
while setting up the resource objects; before the actual repository is called.
Such filters are useful, for example, to implement auditing functionality.

## Filter Priority

`DocumentFilter`, `RepositoryFilter` and `ResourceModificationFilter` can implement
`Prioritizable` to introduce a priority among multiple filters.


anchor:accesshttp[]

## Access to HTTP layer

`HttpRequestContext` resp. `HttpRequestContextProvider` provides access to the HTTP requests. Most
notably to get and set HTTP request and response headers. In many cases, the underlying
implementation like JAXRS or Servlet provides that access as well. With `HttpRequestContext`
there is an implementation that is independent of that implementation. As such it is well suited
for module development, in particular for request filtering. A typical use case is to set and
access security headers.

`HttpRequestContextProvider.getRequestContext` returns the request context for the currently
active request. Modules have access to `HttpRequestContextProvider` trough the `ModuleContext`.
Repositories, filters and modules can implement `HttpRequestContextAware` to get
access to `HttpRequestContextProvider`.


anchor:moduleextensions[]

## Module Extensions and dependencies

ModuleExtension is an interface can can be implemented by modules to specify a contract how
others can extend it. The interface has two mandator properties: targetModule and
optional. targetModule specifies the module consuming those extensions (and providing
the implementation for it). optional specifies whether the target module must be registered
or not. In case of an optional extension without the module being registered, the extension
is simply ignored. The implementing module is free to add any further, custom methods to
provide extension hooks to other modules. To get access to this extensions, the
module can implement ModuleExtensionAware. Extensions must be registered during
Module.setupModule(...) and will be available to the target module when Module.init() is called.

For an example have a look at MetaModuleExtension and the JpaModule making use of it.
The ModuleExtension was introduced with Crnk 2.0 and its use is expected to grow heavily
over time.


anchor:thirdpartystores[]

## Integrate third-party data stores

The core of Crnk is quite flexible when it comes to implementing repositories. As such, it is
not mandatory to make use of the Crnk annotations and conventions. Instead, it is also
(likely) possible to integrate an existing data store setup like JPA, JDBC, ElasticSearch, etc.
into Crnk. For this purpose a module can provide custom implementations of
`ResourceInformationBuilder` and `RepositoryInformationBuilder` trough
`ModuleContext.addResourceInformationBuilder` and `ModuleContext.addRepositoryInformationBuilder`.
For example, the JpaModule of  `crnk-data-jpa` makes use of that to read JPA instead of Crnk annotations.
Such a module can then register additional (usually dynamic) repositories with
`ModuleContext.addRepository`.


anchor:customdiscovery[]

## Implement a custom discovery mechanism

Crnk comes with out-of-the-box support for Spring and CDI. Both of them implement
`ServiceDiscovery`. You may provide your own implementation which can be hooked into the
various Crnk integrations, like the CrnkFeature. Alternatively, it can be auto-detected
through the Java service mechanism. For example, `crnk-cdi` makes use of:

[source]
.META-INF/services/io.crnk.core.module.discovery.ServiceDiscovery
----
include::../../../../crnk-setup/crnk-setup-cdi/src/main/resources/META-INF/services/io.crnk.core.module.discovery.ServiceDiscovery[]
----



Modules have access to that `ServiceDiscovery` trough the `ModuleContext.getServiceDiscovery()`.





## Let a module hook into the Crnk HTTP client implementation

Modules for the Crnk client can additionally implement `HttpAdapterAware`. It gives
the module access to the underlying HTTP client implementation and allows arbitrary
customizations of it. Have a look at the Crnk client documentation for more information.

anchor:customintegration[]

## Implement a custom integration

Adding a new integration has become quite simple in recent times.
Have a look at `crnk-servlet` and `crnk-rs`. Most functionality
necessary is already be provided by `crnk-core`. The steps include:

- implement `HttpRequestContextBase`.
- instantiate `CrnkBoot` to setup crnk.
- get the `RequestDispatcher` from `CrnkBoot`.
- invoke the `RequestDispatcher` for each incoming request with the implemented
  `HttpRequestContextBase`.
- you may want to further implement `SecurityProvider`, `TransactionRunner`
  and `PropertiesProvider` to interface with that particular systems.


anchor:runtimerepository[]

## Create repositories at runtime

Repositories are usually created at compile-time, either by making use of the various annotations or a module
such as the `JpaModule`. However, the module API also allows the creation of repositories at runtime.
There are two complementary mechanisms in place to achieve this and outlined in the next two sections.

NOTE: this feature is in incubation, more refinements are expected in upcoming releases.

### Implementing repositories dynamically at runtime

There are different possibilities to implement resources and repositories at runtime:

1. Create resources classes at runtime with a library like http://bytebuddy.net/#/ to follow the same
  pattern as for any compile-time repository.

2. `JsonAnyGetter` and `JsonAnySetter` annotations from Jackson allow to dynamically add properties to a resource.
  Further implementing `ResourceTypeHolder` interface allows to manipulate the type of a resource. Together
  the annotations allow the implementation of arbitrarily custom resources and type hierarchies. Note that
  when making use of `ResourceTypeHolder` it may also become necessary to register the resource types
  to the `ResourceRegistry` as `RegistryEntry` as outlined in the `Resource` example below.

3. Make use of the `Resource` class. It is the generic JSON:API resource presentation within the Crnk engine.
4. Make use of an arbitrary dynamic object like a `java.util.Map` and provide a `ResourceFieldAccessor` for
  each `ResourceField` to specify how to read and write attributes (see below for `ResourceField` examples).

The use of `JsonAnyGetter` and `JsonAnySetter` is simplest and recommended for most use case.
An example is given in
https://github.com/crnk-project/crnk-example/blob/master/crnk-example-service/src/main/java/io/crnk/example/service/model/PersonEntity.java[PersonEntity]
Nevertheless the direct use of `Resource` opens up the possibility for more deeper control of everything:

[source]
.DynamicResourceRepository.java
----
include::../../../../crnk-test/src/main/java/io/crnk/test/mock/dynamic/DynamicResourceRepository.java[tags=docs1]
...
include::../../../../crnk-test/src/main/java/io/crnk/test/mock/dynamic/DynamicResourceRepository.java[tags=docs2]
----

This new repository can be registered to Crnk with a module:

[source]
.DynamicModule
----
include::../../../../crnk-test/src/main/java/io/crnk/test/mock/dynamic/DynamicModule.java[tags=docs]
----

A new `RegistryEntry` is created and registered with Crnk. It provides information about:

- the resource and all its fields.
- the repositories and instances thereof.

Have a look at the complete example
in https://github.com/crnk-project/crnk-framework/tree/master/crnk-client/src/test/java/io/crnk/client/dynamic[`crnk-client`]
and
https://github.com/crnk-project/crnk-framework/tree/master/crnk-test/src/main/java/io/crnk/test/mock/dynamic[`crnk-test`]
There is a further example test case and relationship repository.

### Registering repositories at runtime

There are two possibilities to register a new repository at runtime:

- by using a `Module` and invoking `ModuleContext.addRegistryEntry` as done in the previous section.
- by implementing a `ResourceRegistryPart` and invoking `ModuleContext.addResourceRegistry`.

The first is well suited if there is a predefined set of repositories that need to be registered
(like a fixed set of JPA entities in the `JpaModule`). The later is suited for fully dynamic use cases where
the set of repositories can change over time (like tables in a database or tasks in an activiti instance). In this
case the repositories no longer need registration. Instead the custom `ResourceRegistryPart` implementation always
provides an up-to-date set of repositories that is used by the Crnk engine.

An example can be found at
https://github.com/crnk-project/crnk-framework/tree/master/crnk-core/src/test/java/io/crnk/core/engine/registry/CustomResourceRegistryTest.java[CustomResourceRegistryTest.java]


anchor:clientmodulediscovery[]

## Discovery of Modules by CrnkClient

If a module does not need configuration, it can provide a `ClientModuleFactory`
implementation and register it to the `java.util.ServiceLoader` by adding a
'META-INF/services/io.crnk.client.module.ClientModuleFactory` file
with the implementation class name. This lets `CrnkClient` discover
the module automatically when calling `CrnkClient.findModules()`.
An example looks like:

[source]
.ValidationClientModuleFactory
----
include::../../../../crnk-validation/src/main/java/io/crnk/validation/internal/ValidationClientModuleFactory.java[]
----

and

[source]
.META-INF/services/io.crnk.client.module.ClientModuleFactory
----
include::../../../../crnk-validation/src/main/resources/META-INF/services/io.crnk.client.module.ClientModuleFactory[]
----



