
# Repositories

The modelled resources and relationships must be complemented by a corresponding
repository implementation. This is achieved by implementing
one of those two repository interfaces:

  * ResourceRepositoryV2 for resources.
  * RelationshipRepositoryV2 resp. BulkRelationshipRepositoryV2 for relationships.

anchor:resource_repository[]

## ResourceRepositoryV2

`ResourceRepositoryV2` is the main interface used to operate on resources with `POST`, `GET`, `PATCH` and `DELETE` requests.
The interface takes two generic arguments:

1. The type of a resource. Typically this is a plain Java Bean making use of the JSON API annotations. But may also be something
  entirely different (see <<architectures> and <<modules>>). One other example is the
  `io.crnk.core.engine.document.Resource` class used to setup dynamically types repositories.
2. The type of the resource’s identifier. Typically a primitive type like `String`, `long` or `UUID`. But if necessary
  can also be a more complex type that serializes to a URL-friendly String.

The methods of `ResourceRepositoryV2` look as follows:

* `findOne(ID id, QuerySpec querySpec)`
  Search one resource with a given ID. If a resource cannot be found, a ResourceNotFoundException exception should be thrown
  that translates into a `404` HTTP error status. The returned resource must adhere to the behavior as specifies by
  the various annotations (more details in the <<resource>> chapter), most notably the inclusion of relationships as requested
  by the passed `querySpec` as long as `LookupIncludeBehavior` does not specify otherwise. More details about `QuerySpec`
  follow in subsequent sections.

* `findAll(Iterable<ID>ids, QuerySpec querySpec)`
  Allows to bulk request multiple resources, but otherwise work exactly like the preceding `findOne` method.

* `findAll(QuerySpec querySpec)`
  Search for all resources according to the passed `querySpec` including sorting, filtering, paging, field sets and inclusions.
  A `ResourceList` must be returned that carries the result resources, links information and meta information.

* `create(S resource)`
  Called by `POST` requests. The request body is deserialized and passed as `resource` parameter. The method may or may
  not have to generate an ID for the newly created resource. The request body may specify relationship data to point to
  other resources. During deserialization, those resources are looked up and the `@JsonApiRelation` annotated fields set
  accordingly. For relationships making use of `@JsonApiRelationId` annotation, only the identifier will be set without
  the resource annotation, allowing to improve for performance. The `create` method has to save those relationships, but
  it does and must not perform any changes on the related resources. For bulk inserting and updating resources, have a look
  at the <<operations_module, operations module>>. The method must return the updated resource, most notably with a valid
  identifier.


* `save(S resource)`
  Saves a resource upon a `PATCH` request. The general semantics is identical to the `create(...)` method, with two
  notable exceptions. First, resources are updated but are not allowed to be inserted.
  A `ResourceNotFoundException` must be thrown if the resource does not exist. Second, the `PATCH` request
  allows for partial updates. Internally Crnk will get the current state of a resource, patch it and pass it to this `save`
  method. API to distinguish patched from un-patched fields is not yet (directly) available, feel free to open a ticket.



* `delete(ID id)`
  Removes a resource identified by id parameter. A `ResourceNotFoundException` must be thrown if the resource does not exist.

The ResourceRepositoryBase is a base class that takes care of some boiler-plate, like implementing findOne with findAll. An
implementation can then look as simple as:

[source]
.Task.java
----
include::../../../../crnk-examples/spring-boot-example/src/main/java/io/crnk/example/springboot/domain/model/Task.java[tag=doc1]
   ...
include::../../../../crnk-examples/spring-boot-example/src/main/java/io/crnk/example/springboot/domain/model/Task.java[tag=doc2]
----

and

[source]
.TaskRepositoryImpl.java
----
include::../../../../crnk-examples/spring-boot-example/src/main/java/io/crnk/example/springboot/domain/repository/TaskRepositoryImpl.java[tag=doc]
----

The example is taken from
https://github.com/crnk-project/crnk-framework/tree/master/crnk-examples/spring-boot-example/src/main/java/io/crnk/example/springboot/domain/repository[crnk-examples/spring-boot-example].
(the basic Spring boot example from crnk-framework, not the dedicated full-blown one from crnk-example).

Together with matching project repository, some URLs to checkout:

[source]
----
http://127.0.0.1:8080/api/tasks
http://127.0.0.1:8080/api/tasks/1
http://127.0.0.1:8080/api/tasks/1
http://127.0.0.1:8080/api/tasks/1/project
http://127.0.0.1:8080/api/tasks/1/relationships/project
http://127.0.0.1:8080/api/tasks?sort=-name
http://127.0.0.1:8080/api/tasks?sort=-id,name
http://127.0.0.1:8080/api/tasks?sort=-id,name
http://127.0.0.1:8080/api/tasks?sort=id&page[offset]=0&page[limit]=2
http://127.0.0.1:8080/api/tasks?filter[name]=Do things
http://127.0.0.1:8080/api/tasks?filter[name][EQ]=Do things
http://127.0.0.1:8080/api/tasks?filter[name][LIKE]=Do
http://127.0.0.1:8080/api/tasks?fields=name
http://127.0.0.1:8080/api/projects
http://127.0.0.1:8080/api/tasks?include=project
http://127.0.0.1:8080/api/browse/
----

You may notice that:

- links get automatically created.
- `totalResourceCount` and pagination links are added to the response if the `page` parameter is applied.
- related `project` gets automatically resolved from `projectId`. No relationship repository is implemented here
  due to the use of `@JsonApiRelationId` (see below).
- the response gets automatically truncated with the `fields` parameter, ideally suited for bandwidth sensitive applications.

This is one small example that *shows the power of native resource-oriented REST libraries*. Implementing a similar API with more
classical REST libraries can be a substantial amount of work.

There is further a `ReadOnlyResourceRepositoryBase` base class that does not allow to override
the create, delete and update methods. `crnk-meta` accordingly reports
insertable, updateable, deltable for such repositories as false.


anchor:relationshipRepository[]

## RelationshipRepositoryV2

IMPORTANT: Before getting started with the development of relationship repositories, familiarize yourself
with <<jsonApiRelation,@JsonApiRelation.repositoryBehavior>>. In various scenarios, a custom implementation is unnecessary!


Each relationship defined in Crnk (annotation @JsonApiRelation) must have a relationship repository
defined implementing `RelationshipRepositoryV2`. `RelationshipRepositoryV2` implements the methods
necessary to work with a relationship. It provides methods for both single-valued and multi-valued
relationships:


* `getMatcher()`
  Provides a  `RelationshipMatcher` instance that specifies which relationships it is able provide.
  It can match against source and target types and fields in any combination. Note that this
  is a default method that access the legacy `getSourceResourceClass` and `getTargetResourceClass`
  by default. Implementation of those methods can be omitted if a matcher is available.

* `setRelation(T source, D_ID targetId, String fieldName)`
  Sets a resource defined by targetId to a field fieldName in an instance source. If no value is to be set, null value is passed.

* `setRelations(T source, Iterable<D_ID> targetIds, String fieldName)`
  Sets resources defined by targetIds to a field fieldName in an instance source. This is a all-or-nothing operation, that is no partial relationship updates are passed. If no values are to be set, empty Iterable is passed.

* `addRelations(T source, Iterable<D_ID> targetIds, String fieldName)`
  Adds relationships to a list of relationships.

* `removeRelations(T source, Iterable<D_ID> targetIds, String fieldName)`
  Removes relationships from a list of relationships.

* `findOneTarget(T_ID sourceId, String fieldName, QuerySpec querySpec)`
  Finds one field's value defined by fieldName in a source defined by sourceId.

* `findManyTargets(T_ID sourceId, String fieldName, QuerySpec querySpec)`
  Finds an Iterable of field's values defined by fieldName in a source defined by sourceId .

All of the methods in this interface have fieldName field as their last parameter in case there
are multiple relationships between two resources.


### Example


[source]
.HistoryRelationshipRepository
----
include::../../../../crnk-examples/spring-boot-example/src/main/java/io/crnk/example/springboot/domain/repository/HistoryRelationshipRepository.java[tag=docs]
----


### RelationshipMatcher

With `RelationshipRepositoryV2.getMatcher()` one has a lot of flexibility about which kind of relationships a repository is
serving. Rules can look like:

[source]
.RelationshipMatcherTest
----
new RelationshipMatcher().rule().source("projects").add().matches(field)
new RelationshipMatcher().rule().target(Task.class).add().matches(field)
new RelationshipMatcher().rule().target(Tasks.class).add().matches(field)
new RelationshipMatcher().rule().field("tasks").add().matches(field)
new RelationshipMatcher().rule().oppositeField("project").add().matches(field)
[source]
----

One can implement, for example, a history relationship repository that introduces a history relationship for every other resource
as done in the example from the previous section.


### ForwardingRelationshipRepository

NOTE: Also have a look at <<jsonApiRelation,@JsonApiRelation.repositoryBehavior>> before getting started to use
this base class.

In many cases, relationship operations can be mapped back to resource repository operations. Making the need
for a custom relationship repository implementation redundant. `@JsonApiRelationId` fields is one example
where Crnk will take care of this automatically. But there are many other scenarios where application apply
similar techniques. A findManyTargets request might can be
served by filtering the target repository. Or a relationship can be set by invoking the save operation
on either the source or target resource repository (usually you want to save on the single-valued side).
The `ForwardingRelationshipRepository` is a base class that takes care of exactly such use cases.
`ForwardingRelationshipRepository` knows to `ForwardingDirection`: `OWNER` and `OPPOSITE`. The former forwards requests
to the resource repository of the owning side of a relationship, while the later forwards to the opposite side.
`ForwardingDirection` is set separately for `GET` and modification operations (`POST`, `PATCH`, `DELETE`).

An example to create such a repository looks like:

[source]
----
RelationshipMatcher taskProjectMatcher = new RelationshipMatcher();
taskProjectMatcher.rule().source(Task.class).target(Project.class).add();

new ForwardingRelationshipRepository(
  Task.class, taskProjectMatcher, ForwardingDirection.OWNER, ForwardingDirection.OWNER
);
----

Note that to access the opposite side for `GET` operations, relations must be set up bidirectionally with the
`opposite` attribute (to allow filtering in that direction):

[source]
----
	@JsonApiResource(type = "tasks")
	public class Task {

		@JsonApiRelation(opposite = "tasks", lookUp = LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL)
		private Project project;

	    ...
	}
----

### BulkRelationshipRepositoryV2

BulkRelationshipRepositoryV2 extends RelationshipRepositoryV2 and provides an additional
`findTargets` method. It allows to fetch a relation for multiple resources at once.
It is recommended to make use of this implementation if a relationship is loaded frequently
(either by a eager declaration or trough the `include` parameter) and it is costly to
fetch that relation. RelationshipRepositoryBase provides a default implementation where
`findOneTarget` and `findManyTargets` forward calls to the bulk `findTargets`.

Note that in contrast to `RelationshipRepositoryV2` and `RelationshipRepositoryV2` that are symmetric
and applicable to Crnk servers and client, `BulkRelationshipRepositoryV2` is applicable on the server-side only.


## ResourceList

ResourceRepositoryV2 and RelationshipRepositoryV2 return lists of type ResourceList. The ResourceList can carry, next
to the actual resources, also meta and links information:

* `getLinks()`
	Gets the links information attached to this lists.

* `getMeta()`
	Gets the meta information attached to this lists.

* `getLinks(Class<L> linksClass)`
	Gets the links information of the given type attached to this lists. If the given type is not found, null is returned.

* `getMeta(Class<M> metaClass)`
	Gets the meta information of the given type attached to this lists. If the given type is not found, null is returned.

There is a default implementation named DefaultResourceList. To gain type-safety, improved readability and crnk-client support,
application may provide a custom implementation extending ResourceListBase:

[source]
----
	class ScheduleList extends ResourceListBase<Schedule, ScheduleListMeta, ScheduleListLinks> {

	}

	class ScheduleListLinks implements LinksInformation {

		public String name = "value";

		...
	}

	class ScheduleListMeta implements MetaInformation {

		public String name = "value";

		...
	}
----

This implementation can then be added to a repository interface declaration
and used by both servers and clients:

[source]
----
	public interface ScheduleRepository extends ResourceRepositoryV2<Schedule, Long> {

		@Override
		public ScheduleList findAll(QuerySpec querySpec);

	}
----




## Query parameters with QuerySpec

Crnk passes JSON API query parameters to repositories trough a QuerySpec parameter. It holds
request parameters like sorting and filtering specified by JSON API. The subsequent
sections will provide a number of example.

NOTE: Not everything is specified by JSON API. For some request parameters only recommendations
are provided as different applications are likely to be in need of different semantics and
implementations. For this reason the engine part in `crnk-core` makes use of `QueryAdapter` and allows implementations other than
QuerySpec (like the legacy `QueryParams`).

For example showing its use URLs also have a look at the <<resource_repository,ResourceRepositoryV2>> section.


### Filtering

NOTE: The JSON API specification does not a mandate a specific filtering semantic. Instead
it provides a recommendation that comes by default with Crnk. Depending on the data store
in use, application may choose to extend or replace that default implementation.

Resource filtering can be achieved by providing parameters which start with `filter`.
The format for filters: `filter[ResourceType][property|operator]([property|operator])* = "value"`

* `GET /tasks/?filter[name]=Super task`
* `GET /tasks/?filter[name][EQ]=Super task`
* `GET /tasks/?filter[tasks][name]=Super task`
* `GET /tasks/?filter[tasks][name]=Super task&filter[tasks][dueDate]=2015-10-01`

QuerySpec uses the `EQ` operator if no operator was provided.

Operators are represented by the `FilterOperator` class. Crnk comes with a set of
default filters:

[cols="1,3", options="header"]
|===
|Name
|Descriptor

|`EQ`
|equals operator where values match exactly.

|`NEQ`
|not equals where values do not match.

|`LIKE`
|where the value matches the specified pattern. It is usually
 not case-sensitive and makes use of `%` as wildclard, but
 may different depending on the underlying implementation.

|`LT`
|lower than the specified value

|`LE`
|lower than or equals the specified value

|`GT`
|greater than the specified value

|`GE`
|greater than or equals the specified value
|===

The application is free to implements its own `FilterOperator`. Next to the name
a `matches` method can be implemented to support in-memory filtering
with `QuerySpec.apply`. Otherwise, it is up to the repository implementation
to handle the various filter operators; usually by translating them
to datastore-native query expressions. Custom operators can be registered
with `DefaultQuerySpecDeserializer.addSupportedOperator(..)`. The default operator can be
overridden by setting `DefaultQuerySpecDeserializer.setDefaultOperator(...)`.


### Sorting

Sorting information for the resources can be achieved by providing `sort` parameter.

* `GET /tasks/?sort=name,-shortName`
* `GET /tasks/?sort[projects]=name,-shortName&include=projects`


anchor:pagination[]

### Pagination

Resources pagination strategies defined by <<jsonApiResourcePagingBehavior,@JsonApiResource.pagingBehavior>>.
By default, each resource has implicit pagination support defined by `OffsetLimitPagingBehavior`.
It provides a simple strategy of a pair `offset/limit` parameters which can be used for filtering amount of results.

Pagination executed automatically as soon as client provides a  `page` parameter.
The format for pagination: `page[offset|limit] = "value", where value is an integer`

Example:

* `GET /tasks/?page[offset]=0&page[limit]=10`


The JSON API specifies `first`, `previous`, `next` and `last` links (see http://jsonapi.org/format/#fetching-pagination).
The `PagedLinksInformation` interface provides a Java representation of those links that can be implemented and returned
by repositories along with the result data. There is a default implementation named `DefaultPagedLinksInformation`.

There are two ways to let Crnk compute pagination links automatically:

1. The repository returns meta information implementing `PagedMetaInformation`. With this interface the total
   number of (potentially filtered) resources is passed to Crnk, which in turn allows the computation of the links.
2. The repository returns meta information implementing `HasMoreResourcesMetaInformation`. This interface
   only specifies whether further resources are available after the currently requested resources. This
   lets Crnk compute all except the `last` link.

Note that for both approaches the repository has to return either no links or links information implementing
`PagedLinksInformation`. If the links are already set, then the computation will be skipped.

The potential benefit of the second over the first approach is that it might be easier to just
determine whether more resources are available rather than counting all resources.
This is typically achieved by querying `limit + 1` resources.

#### Custom strategies

Resources might have custom pagination strategies. In order to do so, you would have to perform the following actions:

1. Provide an instance of a custom `PagingBehavior` implementation.
2. Set it up via <<jsonApiResourcePagingBehavior,@JsonApiResource.pagingBehavior>> attribute.

### Sparse Fieldsets

Information about fields to include in the response can be achieved by providing `fields` parameter.

* `GET /tasks/?fields=name`
* `GET /tasks/?fields[projects]=name,description&include=projects`



### Inclusion of Related Resources

Information about relationships to include in the response can be achieved by providing `include` parameter.
The format for fields: `include[ResourceType] = "property(.property)*"`

Examples:

* `GET /tasks/?include[tasks]=project`
* `GET /tasks/1/?include[tasks]=project`
* `GET /tasks/?include[tasks]=author`
* `GET /tasks/?include[tasks][]=author&include[tasks][]=comments`
* `GET /tasks/?include[projects]=task&include[tasks]=comments`
* `GET /tasks/?include[projects]=task&include=comments` (QuerySpec example)


### API

The QuerySpec API looks like (further setters available as well):

[source]
----
	public class QuerySpec {
		public <T> List<T> apply(Iterable<T> resources){...}

		public Long getLimit() {...}

		public long getOffset() {...}

		public PagingSpec getPagingSpec() {...}

		public List<FilterSpec> getFilters() {...}

		public List<SortSpec> getSort() {...}

		public List<IncludeFieldSpec> getIncludedFields() {...}

		public List<IncludeRelationSpec> getIncludedRelations() {...}

		public QuerySpec getQuerySpec(Class<?> resourceClass) {...}

		...
	}
----

Note that single QuerySpec holds the parameters for a single resource type and,
in more complex scenarios, request can lead to multiple QuerySpec instances
(namely when related resources are also filtered, sorted, etc). A repository
is invoked with the QuerySpec for the requested root type. If related resources are
included in the request, their QuerySpecs can be obtained by calling `QuerySpec.getRelatedSpec(Class)` on the root QuerySpec.

`FilterSpec` holds a value of type object. Since URL parameters are passed as String,
they get converted to the proper types by the `DefaultQuerySpecDeserializer`. The
type is determined based on the type of the filtered attribute.

`PagingSpec` holds a value of defined pagination strategy.
By default, the values can be accessed via `getLimit/getOffset` methods.
In case of custom strategies, `getPagingSpec` should be used.

QuerySpec provides a method `apply` that allows in-memory sorting, filtering and paging
on any `java.util.Collection`. It is useful for testing and on smaller datasets to keep
the implementation of a repository as simple as possible. It returns a ResourceList
that carries a PagedMetaInformation that lets Crnk automatically compute pagination links.



### DefaultQuerySpecDeserializer

Crnk make use of `DefaultQuerySpecDeserializer` to map URL parameters to a QuerySpec instance.
This instance is accessible from the various integrations, such as from the `CrnkFeature`. It
provides a number of customization options:

* `setAllowUnknownAttributes(boolean)`
	`DefaultQuerySpecDeserializer` validates all passed parameters against the domain model and fails
	if one of the attributes is unknown. This flag allows to disable that check in case this should be necessary.

* `setAllowUnknownParameters(boolean)`
	`DefaultQuerySpecDeserializer` validates all passed parameters to be one of the following types: `filter`, `sort`, `page`, `fields` or `include`.
	In case of any custom query parameter `ParametersDeserializationException` will be thrown.
	This flag allows to disable that check and ignore any unknown ones.

* `setIgnoreParseExceptions(boolean)`
	`DefaultQuerySpecDeserializer` attempts to convert all filter parameters to their proper type based on the
	attribute type to be filtered. In some scenarios like dates this behavior may be undesirable as applications
	introduce expressions like 'now`. Enabling this flag will let `DefaultQuerySpecDeserializer` ignore
	such values and provide them as `String` within `FilterSpec`.

* `setEnforceDotPathSeparator(boolean)`
	DefaultQuerySpecDeserializer by default supports by default two URL conventions:
	 `http://.../resource?filter[task][project][name]=myProject` and
	 `http://.../resource?filter[task][project.name]=myProject`. The later is recommended. The former
	 still supported for historic reasons. By default the flag is still disabled, but it is recommended
	 to be packagingEnabled and will become the default at some point in the future. Note that without the enforcement,
	 there is danger of introducing ambiguity with resources and attributes are named equally.


Note that appropriate page limits are vital to protect against denial-of-service attacks when working
with large data sets! Such attacks may not be of malicious nature, but normals users using a browser
and omitting to specify pagination parameters.

`DefaultQuerySpecDeserializer` implements `QuerySpecDeserializer` and you may also provide your own
implementation to further customize its behavior. The various integrations like `CrnkFeature` will
allow to replace the implementation.

One can get access to `DefaultQuerySpecDeserializer` trough the various integrations, e.g.
`CrnkFeature.getQuerySpecDeserializer()`. For more information have a look at the
<<setup,setup chapter>>. Next to the setters in the various integrations, it is also possible
to provide a custom  `QuerySpecDeserializer` trough the
service discovery mechanism (like specifying a Spring or CDI bean).



## Error Handling

Processing errors in Crnk can be handled by throwing an exception and providing
a corresponding exception mapper which defines mapping to a proper JSON API error response.


### Throwing an exception...

Here is an example of throwing an Exception in the code:

[source]
----
  if (somethingWentWrong()) {
    throw new SampleException("errorId", "Oops! Something went wrong.")
  }
----

Sample exception is nothing more than a simple runtime exception:

[source]
----
  public class SampleException extends RuntimeException {

    private final String id;
    private final String title;

    public ExampleException(String id, String title) {
      this.id = id;
      this.title = title;
    }

    public String getId() {
      return id;
    }

    public String getTitle() {
      return title;
    }
  }
----

### ...and mapping it to JSON API response

Class responsible for mapping the exception should:

* implement ExceptionMapper interface
* available trough the used discovery mechanism or added trough a module.

Sample exception mapper:

[source]
.TestExceptionMapper.java
----
include::../../../../crnk-test/src/main/java/io/crnk/test/mock/TestExceptionMapper.java[]
----

On the server-side an exception should be mapped to an `ErrorResponse` object
with `toErrorResponse`. It consists of an HTTP status and `ErrorData` (which is consistent with JSON API error structure).
On the client-side an `ExceptionMapper` returning `true` upon `accept(...)` is used to map an
`ErrorResponse` back to an exception with `fromErrorResponse`.

Note that the exception mapper is reponsible for providing the logging of exceptions with the
appropriate log levels. Also have a look at the subsequent section about the validation module that takes
care of JSR-303 bean validation exception mapping.


## Meta Information

NOTE: With ResourceList and @JsonApiMetaInformation meta information can be returned directly. A MetaRepository implementation is no longer necessary.

There is a special interface which can be added to resource repositories to provide meta information: `io.crnk.core.repository.MetaRepository`.
It contains a single method `MetaInformation getMetaInformation(Iterable<T> resources)` which return meta information object that implements the marker `interface io.crnk.response.MetaInformation`.

If you want to add meta information along with the responses, all repositories (those that implement `ResourceRepository` and `RelationshipRepository`) must implement `MetaRepository`.

When using annotated versions of repositories, a method that returns a `MetaInformation` object should be annotated with `JsonApiMeta` and the first parameter of the method must be a list of resources.

## Links Information

NOTE: With ResourceList and @JsonApiLinksInformation links information can be returned directly. A LinksRepository implementation is usually not necessary.

There is a special interface which can be added to resource repositories to provide links information: `io.crnk.core.repository.LinksRepository`.
It contains a single method `LinksInformation getLinksInformation(Iterable<T> resources)` which return links information object that implements the marker `interface io.crnk.response.LinksInformation`.

If you want to add meta information along with the responses, all repositories (those that implement `ResourceRepository` and `RelationshipRepository`), must implement `LinksRepository`.

When using annotated versions of repositories, a method that returns a `LinksInformation` object should be annotated with `JsonApiLinks` and the first parameter of the method has to be a list of resources.


### Payload Size Optimizations

Self and related links can make up to 60% of the response payload size and not always are those links of use.
Crnk offers a `Crnk-Compact: true` header that can be sent along with the request. In this case the computation
of those links is omitted. Further relationships without data are completely omitted.



## ResourceFieldContributor

The `ResourceFieldContributor` interface allows to dynamically introduce new fields to resources without actually
touching them. This is useful, for example, if you have a JPA entity exposed with crnk-jpa and
want to add further fields like that mentioned history relationship from the earlier relationship example.
`ResourceFieldContributor` can
be implemented by a repository or obtained from the regular service discovery mechanism.

Any type of field can be added: meta, links, attribute and relationship fields. For relationship fields
an application may make use of `RelationshipMatcher` to provide repository serving those fields.
Notice the `accessor` property that is used to obtain the value of that field
(make sure this method is efficient to execute). An example is given by the `HistoryRelationshipRepository` in
https://github.com/crnk-project/crnk-framework/tree/master/crnk-examples/spring-boot-example[crnk-examples/spring-boot-example]:

[source]
.HistoryFieldContributor
----
include::../../../../crnk-examples/spring-boot-example/src/main/java/io/crnk/example/springboot/domain/repository/HistoryFieldContributor.java[tag=docs]
----

- `getRelationshipFields` introduces the field dynamically instead of statically.
- `getMatcher` attaches the repository to the historized resources.
- `findManyTarget` implements the lookup of history elements.