
anchor:resource[]

# Resource

A resource as defined by JSON:API holds the actual data. The engine part of `crnk-core` is agnostic to how such resources are
actually implemented (see the <<architecture>> and <<modules>> chapters). This chapter describes the most common
way Java Beans and annotations. See <<runtimerepository,here>> for more information how setup resources and repositories
programmatically at runtime.

anchor:jsonApiResource[]

## JsonApiResource

It is the most important annotation which defines a resource. It requires type parameter to be defined that is used to form a URLs and type field in passed JSONs. According to JSON:API standard, the name defined in type can be either plural or singular

The example below shows a sample class which contains a definition of a resource.

[source]
----
  @JsonApiResource(type = "tasks")
  public class Task {
    // fields, getters and setters
  }
----

where `type` parameter specifies the resource's name.

By default the type of a resource in a JSON:API document and its name within URLs match, for example:

[source]
----
{
  "links": {
    "self": "http://localhost/api/tasks",
  },
  "data": [{
    "type": "tasks",
    "id": "1",
    "attributes": {
      "title": "Some task"
    }
  }
}
----

The optional `resourcePath` allows to define separate values, typically with `resourcePath` being plural and
`type` being singular:

[source,java]
----
  @JsonApiResource(type = "task", resourcePath = "tasks")
  public class Task {
    // fields, getters and setters
  }
----

resulting in (notice the self link does not change, but type does):

[source]
----
{
  "links": {
    "self": "http://localhost/api/tasks",
  },
  "data": [{
    "type": "task",
    "id": "1",
    "attributes": {
      "title": "Some task"
    }
  }
}
----

anchor:jsonApiResourcePagingBehavior[]

The optional `pagingSpec` parameter allows to set the desired paging specification:

[source,java]
----
  @JsonApiResource(type = "tasks", pagingSpec = OffsetLimitPagingSpec.class)
  public class Task {
    // fields, getters and setters
  }
----

There is built-in support for `OffsetLimitPagingSpec` (default) or `NumberSizePagingSpec`. The paging spec must
be backed by a matching `PagingBehavior` implementation.  More detailed information about pagination can be
found at <<pagination,Pagination>> section.

The optional `subTypes` parameter allows to specify an inheritance relationship to other resources:

[source,java]
----
  @JsonApiResource(type = "task", subTypes = SpecialTask.class)
  public class Task {
    // fields, getters and setters
  }

  @JsonApiResource(type = "specialTask", resourcePath = "task")
  public class SpecialTask extends Task{
    // fields, getters and setters
  }
----

In this case the `SpecialTask` extends `Task` but shares the same `resourcePath`, meaning `SpecialTask` does not bring along
a repository implementation (see next chapter), but is served by the task repository. For a more information have a look at the
<<inheritance>> section.

@JsonApiResource has properties to configure the allowed access modes to a resource:
sortable, filterable, postable, readable, patchable and deletable. An example looks like:

[source,java]
----
include::../../../../crnk-core/src/test/java/io/crnk/core/resource/DefaultResourceInformationProviderTest.java[tags=access]
----

The properties match the ones from @JsonApiField and provide the base line for it.
For example, if a resource does not allow filtering, none of its fields will either.
If one of those properties is attempted to be violated, an error is thrown.


## JsonApiId

Defines a field which will be used as an identifier of a resource.
Each resource requires this annotation to be present on a field which type implements `Serializable` or is of primitive type.

The example below shows a sample class which contains a definition of a field which contains an identifier.

[source,java]
----
@JsonApiResource(type = "tasks")
public class Task {
@JsonApiId
private Long id;

// fields, getters and setters
}
----

anchor:jsonApiRelation[]

## JsonApiRelation

Indicates a relationship to either a single value or collection of resources. The type of such fields
must be a valid resource. The next example showcases a bi-directional relationship between `Task` and `Project`:

[source,java]
----
@JsonApiResource(type = "tasks")
public class Task {

    @JsonApiRelation
    private Project project;

    ...
}

@JsonApiResource(type = "project")
public class Project {

    @JsonApiRelation(mappedBy="project")
    private Set<Task> tasks;

    ...
}
----

The `project` and `tasks` field are linked through the `mappedBy` property by pointing from the non-owning
to the owning field of the relationship. `project` as owning field will be used for all read and update operations. This
means:

- for `GET /api/projects?include=tasks` and `GET /api/projects/{id}/tasks`, first the projects are loaded and then
  a query is issued against the repository of `Task` with a filter `project.id = {list of project ids}`.
- for `PATCH/POST/DELETE /api/project/{id}/tasks`, the request is forwarded
  to the `Task` repository by setting the `project` field and saving the updated resources.
- for `PATCH/POST /api/projects/{id}` the `tasks` attribute can by default not be modified because it is not the owner
  of the relationships. But repositories are free to implement this functionality if desired.

Behind the scenes `mappedBy` makes use of the `FORWARD_OPPOSITE` repository behavior whereas the opposite
makes use of `FORWARD_OWNER` that are explained further down in this section. As such `mappedBy` can be
considered to be a shortcut for setting various other notifications that is useful in many scenarios.
The semantics of `mappedBy` matches with the concepts of, for example, JPA-related annotations.
It is typical for single-valued fields like `project` to be the owner. Such fields are usually backed by something like
a column in a database and are simple to read and write. In contrast,
multi-valued fields like `tasks` can only be obtained by issuing a query against the single-valued counter-part.
In such a setting, it might proof useful to to make use of <<jsonApiRelationId,@JsonApiRelationId>>
on the owning side (introduced in the next section).

@JsonApiRelation comes with a number of attributes to customize its behavior.
<<jsonApiRelationId,@JsonApiRelationId>> as complementary annotation is introduced in the subsequent section.

[source,java]
----
@JsonApiRelation(serialize = SerializeType.ONLY_ID)
private Project project;
----

The optional `serialize` parameter specifies how an association should be serialized when making a request.
There are two things to consider. Whether related resources should be added to the `include` section of the
response document. And whether the id of related resources should be serialized along with the resource
in the corresponding `relationships.[name].data` section. Either `LAZY`, `ONLY_ID` or `EAGER` can be specified:

- `LAZY` only serializes the ID and does the inclusion if explicitly requested by the `include` URL parameter. This is the default.
- `ONLY_ID` always serializes the ID, but does only to an inclusion  if explicitly requested by the `include` URL parameter.
- `EAGER` always both serializes the ID and does an inclusion. Be aware of performance implication when enabling this.

[source,java]
----
@JsonApiRelation(lookUp = LookupIncludeBehavior.AUTOMATICALLY_ALWAYS)
private Project project;
----

JSON:API comes with support for inclusions based on the `include` parameter. It allows to request complex
object graphs where also related resources can be fetched.  There are two possibilities of how this is implemented.
Either the requested repository also directly returns related resources with the returned ones. Or Crnk can take-over that
work by doing nested calls to adjacent `ResourceRepository`, `OneRelationshipRepository` and `ManyRelationshipRepository`
implementations. The behavior is controlled by the optional `lookUp` parameter. There are four options:

- `NONE` makes the requested repository responsible for returning related resources.
- `AUTOMATICALLY_WHEN_NULL` will let Crnk lookup related resources if not already done by the requested repository.
- `AUTOMATICALLY_ALWAYS` will force Crnk to always lookup related resource regardless whether it is already done by the requested repository.
- `DEFAULT` attempts to find the optimal setting automatically. If a custom relationship repository is found,
  `@JsonApiRelationId` is in use or `@JsonApiRelation.repositoryBehavior` fetches from the opposite side, then
   `AUTOMATICALLY_WHEN_NULL` is chosen, otherwise it falls back to `NONE`. This default behavior should
   be sufficient for most use cases.

There are many different ways how a relationship may end-up being implemented. In the best case, no implementation is necessary
at all and requests can be dispatches to one of the two related resource repositories. The `repositoryBehavior` allows
to configure behavior:

- `CUSTOM` expects a custom implementation.
- `FORWARD_OWNER` forward any relationship request to the owning resource repository, the repository that defines the
  requested relationship field. GET requests will fetch the owning resources and grab the related resources from there (with the
  appropriate inclusion parameter). This assumes that the owning resource properties hold the related resources
  (or at least there IDs in case of `JsonApiRelationId`, see below).
  POST, PATCH, DELETE requests will update the properties of the owning resource accordingly and invoke a save operation on the
  owning resource repository. An implementation is provided by `ImplicitOwnerBasedRelationshipRepository`.
- `FORWARD_GET_OPPOSITE_SET_OWNER` works like `FORWARD_OWNER` for PATCH, POST, DELETE methods. In contrast,
  GET requests are forwarded to the opposite resource repository. For example,
	  if there is a relationship between `Task` and `Project` with the `project` and `tasks` relationship fields. To get all tasks of
	  a project, the task repository will be queried with a `project.id=<projectId>` filter parameter.
	  Relational database are one typical example where this pattern fits nicely. In contract to `IMPLICIT_FROM_OWNER` only a
	  single resource repository is involved with a slightly more complex filter parameter, giving performance benefits.
	  An implementation is provided by `RelationshipRepositoryBase`.
- `FORWARD_OPPOSITE` the opposite to `FORWARD_OWNER`. Querying works like `IMPLICIT_GET_OPPOSITE_MODIFY_OWNER`.
- `DEFAULT` makes use of `FORWARD_OWNER` if the relationship makes use of `@JsonApiRelationId` (see below),
   `lookUp=NONE` or `lookUp=DEFAULT`. `FORWARD_OPPOSITE` if `mappedBy` points to another field. `CUSTOM` if a
    matching relationship repository is found. For all other scenarios it it expects a custom implementation.

The forwarding behaviors are implemented by `ForwardingRelationshipRepository`.

The subsequent two resources show case a number of scenarios:

[source,java]
----
@JsonApiResource(type = "task")
public class Task {
    @JsonApiId
    public String id;

    @JsonApiRelation // not backed by repository
    public Project project;

    @JsonApiRelation // backed by repository
    public List<Task> subTasks;
}

@JsonApiResource(type = "project")
public class Project {
    @JsonApiId
    public String id;

    @JsonApiRelation(mappedBy = "project")
    public Set<Task> tasks;

    @JsonApiRelationId
    public Project parentId;

    @JsonApiRelation
    public Project parent;
}

class SubTaskRepository extends OneRelationshipRepositoryBase {
    @Override
    public RelationshipMatcher getMatcher() {
        RelationshipMatcher matcher = new RelationshipMatcher();
        matcher.rule().field("subTasks").add();
        return matcher;
    }
    ...
}
----

- `parent` has a `@JsonApiRelationId` backed by `parentId`. This triggers the use
  of `RelationshipRepositoryBehavior.FORWARD_OWNER` and `LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL`.
  Only `parentId` must be populated by the project resource repository, `project` can
  then be looked up on the opposite resource repository (which in this case is the same repository).
- `project` just carries an empty `@JsonApiRelation` and has no relationship repository backing it. This
  triggers the assumption that the resource repository can handle all requests, translating to
  `LookupIncludeBehavior.NONE` and `RelationshipRepositoryBehavior.FORWARD_OWNER`.
- `tasks` declares a `mappedBy` to its owner `project`. Accordingly all requests go with
  `RelationshipRepositoryBehavior.FORWARD_OPPOSITE` to the opposite task resource repository. Inclusions
  are resolved automatically with `LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL`.
- `subTasks` is backed by the `SubTaskRepository` relationship repository. This
  sets `RelationshipRepositoryBehavior.CUSTOM` and performs look-ups on that repository with
  `LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL` to compute the inclusions.


IMPORTANT: It likely takes a moment to familiarize oneself with all configuration options of `@JsonApiRelation` and the
  subsequent `@JsonApiRelationId`. But at the same time it is one area where a native resource-oriented REST library like Crnk
  can provide significant benefit and reduce manual work compared to more classical REST libraries like Spring MVC or JAX-RS.

IMPORTANT: If you run into problems in this area, set `io.crnk` to `DEBUG` in your logger. It will print information such as:

[source]
----
20:04:50 DEBUG io.crnk.test.mock.models.Schedule.project: using configured LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL
20:04:50 DEBUG io.crnk.test.mock.models.Schedule.projects: using configured LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL
20:04:50 DEBUG io.crnk.test.mock.models.Schedule.tasks: choosing default RelationshipRepositoryBehavior: mappedBy enforces FORWARD_OPPOSITE
20:04:50 DEBUG io.crnk.test.mock.models.Schedule.tasks: setting up opposite/opposite forwarding repository
20:04:50 DEBUG io.crnk.test.mock.models.Schedule.tasks: RelationshipRepositoryBehavior.FORWARD_OPPOSITE enforces LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL to resolve relationship from opposite side
20:04:50 DEBUG io.crnk.test.mock.models.Schedule.project: choosing default RelationshipRepositoryBehavior: relationId field enforces FORWARD_OWNER
20:04:50 DEBUG io.crnk.test.mock.models.Schedule.project: setting up owner/owner forwarding repository
20:04:50 DEBUG io.crnk.test.mock.models.Schedule.projects: choosing default RelationshipRepositoryBehavior: relationId field enforces FORWARD_OWNER
20:04:50 DEBUG io.crnk.test.mock.models.Schedule.projects: setting up owner/owner forwarding repository
----


anchor:jsonApiRelationId[]

## JsonApiRelationId

Fields annotated with `@JsonApiRelation` hold fully-realized related resources. There are situations
where the id of a related resource is available for free or can be obtained much more cheaply then
fetching the entire related resource. In this case resources can make use of fields annotated with
`@JsonApiRelationId`. The complement `@JsonApiRelation` fields by holding there ID only.
An example looks like:

[source,java]
----
@JsonApiResource(type = "schedules")
public class Schedule {
  ...

  @JsonApiRelationId
  private Long projectId;

  @JsonApiRelation
  private Project project;

  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(Long projectId) {
    this.projectId = projectId;
    this.project = null;
  }

  public Project getProject() {
    return project;
  }

  public void setProject(Project project) {
    this.projectId = project != null ? project.getId() : null;
    this.project = project;
  }
}
----

Notice that:
- `Schedule` resource holds both a `project` and `projectId` field that point to the same related resource.
- setters must set both properties to make sure they stay in sync. If only the ID is set, the object must be nulled.
- `propertyId` will never show in requests and responses. It can be considered to be `transient`.
- Bi-directional relationships can simply make use of `@JsonRelationId(mappedBy="project")` on the other side.

By default, the naming convention for `@JsonApiRelationId` field is to end with a `Id` or `Ids` suffix. Crnk will
the pair those two objects automatically. Trailing `s` are ignored for multi-valued fields, meaning that `projectIds` matches with
 `projects`. But it is also possible to specify a custom name, for example:

[source,java]
----
@JsonApiRelationId
private Long projectFk;

@JsonApiRelation(idField = "projectFk")
private Project project;
----

If a `@JsonApiRelationId` field cannot be matched to a `@JsonApiRelation` field, an exception will be thrown.

`@JsonApiRelationId` fields are used for:

- `GET` requests to fill-in the `data` section of a relationship.
- `POST` and `PATCH` requests to fill-in the new value without having to fetch and set the entire related resource.

*Further (substantial) benefit for `@JsonApiRelationId` fields is that no `RelationshipRepository`
must be implemented*. Instead Crnk will automatically dispatch relationship requests to the owning and
opposite `ResourceRepository`. This allows to focus on the development of `ResourceRepository`.
See <<relationshipRepository,RelationshipRepository>> for more information.

Next to plain Java objects, many other libraries support this kind of semantic of having two attributes
referring to the same data. For example in JPA this looks like:

[source,java]
----
@JsonApiRelationId
@Column(name = "project_id")
private Long projectId;

@OneToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "project_id", insertable = false, updatable = false)
private ProjectEntity project;
----

Because two fields are mapped to the same column, one must be set to a read-only mode.

## JsonApiMetaInformation

Field or getter annotated with `JsonApiMetaInformation` are marked to carry a `MetaInformation` implementation.
See http://jsonapi.org/format/#document-meta for more information about meta data. Example:

[source,java]
----
	@JsonApiResource(type = "projects")
	public class Project {

		...

		@JsonApiMetaInformation
		private ProjectMeta meta;

		public static class ProjectMeta implements MetaInformation {

			private String value;

			public String getValue() {
				return value;
			}

			public void setValue(String value) {
				this.value = value;
			}
		}
	}
----



## JsonApiLinksInformation

Field or getter annotated with `JsonApiLinksInformation` are marked to carry a `LinksInformation` implementation.
See http://jsonapi.org/format/#document-links for more information about linking. Example:


[source,java]
----
	@JsonApiResource(type = "projects")
	public class Project {

		...

		@JsonApiLinksInformation
		private ProjectLinks links;

		public static class ProjectLinks implements LinksInformation {

			private String value;

			public String getValue() {
				return value;
			}

			public void setValue(String value) {
				this.value = value;
			}
		}
	}
----

Links can be represented either as either simple String:

----
"http://example.com/articles/1/relationships/comments",
----

or as structured objects of type `Link` with
`href`, `rel`, `anchor`, `params`, `describedBy` and `meta` fields:

----
"links": {
	"self": "http://example.com/articles/1/relationships/comments",
		"related": {
			"href": "http://example.com/articles/1/comments",
			"describedby": "http://example.com/schemas/article-comments",
			"meta": {
				"count": 10
			}
		}
	}
}
----

`LinksInformation` objects can hold either type. With `DefaultLink` there is a default implementation
of  `Link` available. By default simple strings will be serialized as such:
----
"links": {
  "self": "http://example.com/posts"
}
----

This can be changed by setting the property `crnk.config.serialize.object.links=true`:

----
"links": {
  "self": {
    "href": "http://example.com/posts",
  }
}
----

There are a variety of interfaces for built-in link types:

- `SelfLinksInformation`
- `RelatedLinksInformation`
- `PagingLinksInformation`

Such links will be populated automatically by Crnk if not specified otherwise.
It is important to highlight that many links can and are derived from the `self` link.
For example, if the `self` link is customized, all relationship links will be adjusted
accordingly.

TIP: If you have use cases where the link can be derived from the `self` link, it can
  be the easiest solution to implement that logic directly in the getter:

----
	public static class ProjectLinks implements LinksInformation, SelfLinksInformation {

		private String value;

		private String self;

		public String getValue() {
			if(value == null && self != null){
				return self + "/foo";
			}
			return value;
		}
		...
	}
----

TIP: `CrnkBoot.getUrlBuilder()` gives access to the `UrlBuilder` class that allows the construction
  of URLs from resources. Ìt is also, for example, defined as Spring bean and can be
  injected into any class.


anchor:jsonApiField[]


## JsonApiField

Field or getter annotated with `@JsonApiField` allows to define  the behavior of an individual attribute. Example:

[source,java]
----
	@JsonApiResource(type = "projects")
	public class Project {

		...

		@JsonApiField(postable=true, patchable=false, sortable=false, filterable=false)
		private Long projectId;

		...
	}
----

Following options are supported:

- `sortable` defines whether a field can be sorted.
- `filterable` defines whether a field can be filtered.
- `postable` defines whether a field can be set with a POST request.
- `patchable` defines whether a field can be changed with a PATCH request.
- `deletable` defines whether a multi-valued relationship field can be changed with a DELETE request.
- `readable` defines whether a field can be read with a GET request.
- `patchStrategy` defines the behavior of value with PATCH request. It can be either `MERGE` if you want the value be merged with an original one or `SET` if you want the value be totaly replaced with a new one.

The same fields are available from <<jsonApiResource,@JsonApiResource>> to configure a default for all fields of that
resource.

anchor:jackson_annotations[]

## Jackson annotations

Crnk comes with (partial) support for Jackson annotations. Currently supported are:

[cols="30,70"]
|===
| Annotation           		| Description

| `@JsonIgnore`
| Excludes a given attribute from serialization.

| `@JsonProperty.value`
| Renames an attribute during serialization.

| `@JsonProperty.access`
| Specifies whether an object can be read and/or written.

| `JsonInclude.Include.NON_EMPTY` and `JsonInclude.Include.NON_NULL`
| Specifies whether null and empty values are omitted from serialization.

| `@JsonAnyGetter` and `@JsonAnySetter`
| To map dynamic data structures to JSON. For an example have a look at
  https://github.com/crnk-project/crnk-example/blob/master/crnk-example-service/src/main/java/io/crnk/example/service/model/PersonEntity.java[PersonEntity]
  from the example application.

|===

Support for more annotations will be added in the future. PRs welcomed.


anchor:nested_resources[]

## Optional values

Crnk comes with support for `java.util.Optional`. Serialization of such fields is omitted if no value is present.
For this to work properly, the `Jdk8Module`` module must be registered with Jackson. It is available from:

----
	<dependency>
		<groupId>com.fasterxml.jackson.datatype</groupId>
		<artifactId>jackson-datatype-jdk8</artifactId>
		<version>${JACKSON_VERSION}</version>
	</dependency>
----

More information can be found in https://www.baeldung.com/jackson-optional.


## Nested Resources

WARNING: This feature is experimental and will be refined in subsequent releases.

A resource may be nested and belong to a parent resource. URLs then look like:

- `http://example.com/posts/1/header` (single)
- `http://example.com/posts/1/comments/2` (multiple)

Here a `post` resource holds two nested relationships: `header` and `comments`. Both of those relationships have resources
that cannot exist without the `post` itself. The former case the relationship holds a single resource, while the later
there might be multiple comments.

Nested resources are implemented like any other resource, most notably by providing a resource repository.
The subsequent two section go into detail how to setup such resources.

### Single Nested Resources

Single nested resources share the identifier with the parent resource. From the example aboce:

`http://example.com/posts/1/header`

Both the `post` and its `header` share the identifier `1`. A resource looks like:

[source,java]
.PostHeader.java
----
include::../../../../crnk-test/src/main/java/io/crnk/test/mock/models/nested/PostHeader.java[tags=docs]
----

Notice the `nested = true` and that the ID also serves as `@JsonApiRelationId` to point to the parent `post`. This two
properties introduce the singular nesting to the resource. The repository itself can then be implemented like any other
repository.

### Multiple Nested Resources

To nest multiple resource below a parent, structured identifier can be used:

[source,java]
.PostCommendId.java
----
include::../../../../crnk-test/src/main/java/io/crnk/test/mock/models/nested/PostCommentId.java[tags=docs]
----

The id is setup of two parts:

- the local identifier of the child resource, annotated with `@JsonApiId`. It must be unique among all nested resources having the same parent.
- the identifier of the parent resource, annotated with a `@JsonApiRelationId`. The nested resource must have matching relationship field (in this case `parent`)`.

`PostCommentId` further implements `public PostCommentId(String idString)`, `toString`, `hashCode` and `equals` and carries the
`@JsonSerialize(using = ToStringSerializer.class)` annotation to deal with String serialization and equality.

The resource itself looks like:

[source,java]
.PostComment.java
----
include::../../../../crnk-test/src/main/java/io/crnk/test/mock/models/nested/PostComment.java[tags=docs]
----

### Usage

For an example have a look at `NestedRepositoryClientTest` and its parent class. Depending on the use of <<JsonApiExposed>> it
is or is not be possible to also directly access `http://example.com/comments` without going
through the parents.

When creating new resources with CrnkClient, the nested identifier must be set to let CrnkClient access the postId
to compute URLs.

WARNING: Nesting is currently limited to a single level (and the possibility to have further relationships on the nested resource).


## @JsonApiVersion

WARNING: This feature is experimental

Crnk supports versioning of resources and fields based on content negotiation.
Any resource and field can carry a version range where it is available.
Crnk will disregard any resource and field with a version range that does not intersect with the request version.
The HTTP `Accept` header is used to pass along the desired version as part of general content negotiation.
This has the benefit that URLs remain constant across versions, greatly simplifying usability and linking.
For a more detailed discussion, see here[https://blog.ploeh.dk/2015/06/22/rest-implies-content-negotiation/].

A versioned resource looks like:

[source,java]
.VersionedTask.java
----
include::../../../../crnk-test/src/main/java/io/crnk/test/mock/models/VersionedTask.java[tags=docs]
----

- The resource itself is available up to version 5.
- The field `completed` is only available from version 1 to 3.
- The field `newCompleted` introduces a new flavor of `completed` making use of `CompletionStatus` rather than
  a boolean. Through the use of `@JsonProperty` it is mapped to `completed` on the REST layer whereas
  the Java side has access to both the old and new field.

Crnk makes use of integer-based version number to signal major versions with breaking changes. There is
no need for minor versions in this scheme. But applications are free to use additional minor versions in other contexts.

A request than carries an accept header like:

----
GET /api/versionedTask HTTP/1.1
Accept: application/vnd.api+json; version=2
----

Alternatively, the version can be passed as URL parameter (easier to use from a browser:

----
GET /api/versionedTask?version=2 HTTP/1.1
Accept: application/vnd.api+json
----

<<client,CrnkClient>> supports setting the request version through `CrnkClient.setVersion(...)`.

Not supported is:

- ID fields cannot be versioned.
- for multiple classes to serve the same resource for different version ranges.
  For example, it is not possible to introduce a class `VersionedTaskV2.java`.
  For most use cases it should be sufficient to redefine fields. This may change in the future
- Meta and link fields cannot be versioned, this may change in the future.

