
anchor:resource[]

# Resource

A resource as defined by JSON API holds the actual data. The engine part of `crnk-core` is agnostic to how such resources are
actually implemented (see the <<architecture>> and <<modules>> chapters). This chapter describes the most common
way Java Beans and annotations. See <<runtimerepository,here>> for more information how setup resources and repositories
programmatically at runtime.


## JsonApiResource

It is the most important annotation which defines a resource. It requires type parameter to be defined that is used to form a URLs and type field in passed JSONs. According to JSON API standard, the name defined in type can be either plural or singular

The example below shows a sample class which contains a definition of a resource.

[source]
----
  @JsonApiResource(type = "tasks")
  public class Task {
    // fields, getters and setters
  }
----

where `type` parameter specifies the resource's name.

By default the type of a resource in a JSON API document and its name within URLs match, for example:

[source]
----
{
  "links": {
    "self": "http://localhost/api/tasks",
  },
  "data": [{
    "type": "tasks",
    "id": "1",
    "attributes": {
      "title": "Some task"
    }
  }
}
----

The optional `resourcePath` allows to define separate values, typically with `resourcePath` being plural and
`type` being singular:

[source]
----
  @JsonApiResource(type = "task", resourcePath = "tasks")
  public class Task {
    // fields, getters and setters
  }
----

resulting in (notice the self link does not change, but type does):

[source]
----
{
  "links": {
    "self": "http://localhost/api/tasks",
  },
  "data": [{
    "type": "task",
    "id": "1",
    "attributes": {
      "title": "Some task"
    }
  }
}
----

anchor:jsonApiResourcePagingBehavior[]

The optional `pagingSpec` parameter allows to set the desired paging specification:

[source]
----
  @JsonApiResource(type = "tasks", pagingSpec = OffsetLimitPagingSpec.class)
  public class Task {
    // fields, getters and setters
  }
----

There is built-in support for `OffsetLimitPagingSpec` (default) or `NumberSizePagingSpec`. The paging spec must
be backed by a matching `PagingBehavior` implementation.  More detailed information about pagination can be
found at <<pagination,Pagination>> section.

The optional `subTypes` parameter allows to specify an inheritance relationship to other resources:

[source]
----
  @JsonApiResource(type = "task", subTypes = SpecialTask.class)
  public class Task {
    // fields, getters and setters
  }

  @JsonApiResource(type = "specialTask", resourcePath = "task")
  public class SpecialTask extends Task{
    // fields, getters and setters
  }
----

In this case the `SpecialTask` extends `Task` but shares the same `resourcePath`, meaning `SpecialTask` does not bring along
a repository implementation (see next chapter), but is served by the task repository. For a more information have a look at the
<<inheritance>> section.



## JsonApiId

Defines a field which will be used as an identifier of a resource.
Each resource requires this annotation to be present on a field which type implements `Serializable` or is of primitive type.

The example below shows a sample class which contains a definition of a field which contains an identifier.

[source]
----
  @JsonApiResource(type = "tasks")
  public class Task {
    @JsonApiId
    private Long id;

    // fields, getters and setters
  }
----

anchor:jsonApiRelation[]

## JsonApiRelation

Indicates an association to either a single value or collection of resources. The type of such fields
must be a valid resource.

The example below shows a sample class which contains this kind of relationship.


[source]
----
  @JsonApiResource(type = "tasks")
  public class Task {

    // ID field

    @JsonApiRelation(lookUp=LookupIncludeBehavior.AUTOMATICALLY_WHEN_NULL,serialize=SerializeType.ONLY_ID)
    private Project project;

    // fields, getters and setters
  }
----


The optional `serialize` parameter specifies how the association should be serialized when making a request.
There are two things to consider. Whether related resources should be added to the `include` section of the
response document. And whether the id of related resources should be serialized along with the resource
in the corresponding `relationships.[name].data` section. Either `LAZY`, `ONLY_ID` or `EAGER` can be specified:

- `LAZY` only serializes the ID and does the inclusion if explicitly requested by the `include` URL parameter. This is the default.
- `ONLY_ID` always serializes the ID, but does only to an inclusion  if explicitly requested by the `include` URL parameter.
- `EAGER` always both serializes the ID and does an inclusion.

There are two possibilities of how related resources are fetched. Either the requested repository directly
returns related resources with the returned resources. Or Crnk can take-over that
work by doing nested calls to the corresponding `RelationshipRepositoryV2` implementations. The behavior
is controlled by the optional `lookUp` parameter. There are three options:

- `NONE` makes the requested repository responsible for returning related resources. This is the default.
- `AUTOMATICALLY_WHEN_NULL` will let Crnk lookup related resources if not already done by the requested repository.
- `AUTOMATICALLY_ALWAYS` will force Crnk to always lookup related resource regardless whether it is already done by the requested repository.

There are many different ways how a relationship may end-up being implemented. In the best case, no implementation is necessary
at all and requests can be dispatches to one of the two related resource repositories. The `repositoryBehavior` allows
to configure behavior:

- `DEFAULT` makes use of `IMPLICIT_FROM_OWNER` if a relationship also makes use of `@JsonApiRelationId` (see below) or
  `lookUp=NONE` (see above). In any other case it expects a custom implementation.
- `CUSTOM` expects a custom implementation.
- `FORWARD_OWNER` forward any relationship request to the owning resource repository, the repository that defines the
  requested relationship field. GET requests will fetch the owning resources and grab the related resources from there (with the
  appropriate inclusion parameter). This assumes that the owning resource properties hold the related resources
  (or at least there IDs in case of `JsonApiRelationId`, see below).
  POST, PATCH, DELETE requests will update the properties of the owning resource accordingly and invoke a save operation on the
  owning resource repository. An implementation is provided by `ImplicitOwnerBasedRelationshipRepository`.
- `FORWARD_GET_OPPOSITE_SET_OWNER` works like `FORWARD_OWNER` for PATCH, POST, DELETE methods. In contrast,
  GET requests are forwarded to the opposite resource repository. For example,
	  if there is a relationship between `Task` and `Project` with the `project` and `tasks` relationship fields. To get all tasks of
	  a project, the task repository will be queried with a `project.id=<projectId>` filter parameter.
	  Relational database are one typical example where this pattern fits nicely. In contract to `IMPLICIT_FROM_OWNER` only a
	  single resource repository is involved with a slightly more complex filter parameter, giving performance benefits.
	  An implementation is provided by `RelationshipRepositoryBase`.
- `FORWARD_OPPOSITE` the opposite to `FORWARD_OWNER`. Querying works like `IMPLICIT_GET_OPPOSITE_MODIFY_OWNER`.

The forwarding behaviors are implemented by `ForwardingRelationshipRepository`.

IMPORTANT: It likely takes a moment to familiarize oneself with all configuration options of `@JsonApiRelation` and the
  subsequent `@JsonApiRelationId`. But at the same time it is one area where a native resource-oriented REST library like Crnk
  can provide significant benefit and reduce manual work compared to more classical REST libraries like Spring MVC or JAX-RS.


anchor:jsonApiRelationId[]

## JsonApiRelationId

Fields annotated with `@JsonApiRelation` hold fully-realized related resources. There are situations
where the id of a related resource is available for free or can be obtained much more cheaply then
fetching the entire related resource. In this case resources can make use of fields annotated with
`@JsonApiRelationId`. The complement `@JsonApiRelation` fields by holding there ID only.
An example looks like:

[source]
----
@JsonApiResource(type = "schedules")
public class Schedule {
  ...

  @JsonApiRelationId
  private Long projectId;

  @JsonApiRelation
  private Project project;

  public Long getProjectId() {
    return projectId;
  }

  public void setProjectId(Long projectId) {
    this.projectId = projectId;
    this.project = null;
  }

  public Project getProject() {
    return project;
  }

  public void setProject(Project project) {
    this.projectId = project != null ? project.getId() : null;
    this.project = project;
  }
}
----

Notice that:
- `Schedule` resource holds both a `project` and `projectId` field that point to the same related resource.
- setters must set both properties to make sure they stay in sync. If only the ID is set, the object must be nulled.
- `propertyId` will never show in requests and responses. It can be considered to be `transient`.

By default, the naming convention for `@JsonApiRelationId` field is to end with a `Id` or `Ids` suffix. Crnk will
the pair those two objects automatically. Trailing `s` are ignored for multi-valued fields, meaning that `projectIds` matches with
 `projects`. But it is also possible to specify a custom name, for example:

[source]
----
@JsonApiRelationId
private Long projectFk;

@JsonApiRelation(idField = "projectFk")
private Project project;
----

If a `@JsonApiRelationId` field cannot be matched to a `@JsonApiRelation` field, an exception will be thrown.

`@JsonApiRelationId` fields are used for:

- `GET` requests to fill-in the `data` section of a relationship.
- `POST` and `PATCH` requests to fill-in the new value without having to fetch and set the entire related resource.

*Further (substantial) benefit for `@JsonApiRelationId` fields is that no `RelationshipRepository`
must be implemented*. Instead Crnk will automatically dispatch relationship requests to the owning and
opposite `ResourceRepository`. This allows to focus on the development of `ResourceRepository`.
See <<relationshipRepository,RelationshipRepository>> for more information.



## JsonApiMetaInformation

Field or getter annotated with `JsonApiMetaInformation` are marked to carry a `MetaInformation` implementation.
See http://jsonapi.org/format/#document-meta for more information about meta data. Example:

[source]
----
	@JsonApiResource(type = "projects")
	public class Project {

		...

		@JsonApiMetaInformation
		private ProjectMeta meta;

		public static class ProjectMeta implements MetaInformation {

			private String value;

			public String getValue() {
				return value;
			}

			public void setValue(String value) {
				this.value = value;
			}
		}
	}
----



## JsonApiLinksInformation

Field or getter annotated with `JsonApiLinksInformation` are marked to carry a `LinksInformation` implementation.
See http://jsonapi.org/format/#document-links for more information about linking. Example:


[source]
----
	@JsonApiResource(type = "projects")
	public class Project {

		...

		@JsonApiLinksInformation
		private ProjectLinks links;

		public static class ProjectLinks implements LinksInformation {

			private String value;

			public String getValue() {
				return value;
			}

			public void setValue(String value) {
				this.value = value;
			}
		}
	}
----

By default links are serialized as:

----
"links": {
  "self": "http://example.com/posts"
}
----

With `crnk.config.serialize.object.links=true` links get serialized as:

----
"links": {
  "self": {
    "href": "http://example.com/posts",
  }
}
----




anchor:jackson_annotations[]

## Jackson annotations

Crnk comes with (partial) support for Jackson annotations. Currently supported are:

[cols="30,70"]
|===
| Annotation           		| Description

| `@JsonIgnore`
| Excludes a given attribute from serialization.

| `@JsonProperty.value`
| Renames an attribute during serialization.

| `@JsonProperty.access`
| Specifies whether an object can be read and/or written.

| `@JsonAnyGetter` and `@JsonAnySetter`
| To map dynamic data structures to JSON.

|===

Support for more annotations will be added in the future. PRs welcomed.


anchor:nested_resources[]

## Nested Resources

WARNING: This feature is experimental and will be refined in subsequent releases.

A resource may be nested and belong to a parent resource. In this case the nested resource is access through its parent resource.
An URL then looks like:

`http://example.com/posts/1/comments/2`

For a resource to become nested, it must make use of a structured identifier:

[source]
.NestedId.java
----
include::../../../../crnk-test/src/main/java/io/crnk/test/mock/models/nested/NestedId.java[]
----

The id is setup of two parts:

- the local identifier of the child resource, annotated with `@JsonApiId`. It must be unique among all nested resources having the same parent.
- the identifier of the parent resource, annotated with a `@JsonApiRelationId`. The nested resource must have matching relationship field (in this case `parent`)`.

`NestedId` further implements `parse`, `toString`, `hashCode` and `equals` to deal with String serialization and equality.

For an example have a look at `NestedRepositoryClientTest` and its parent class. Depending on the use of <<JsonApiExposed>> it
is or is not be possible to also directly access `http://example.com/comments` without going
through the parents.

Current Limitations:

- Nesting is currently limited to a single level (and the possibility to have further relationships on the nested resource).
- When creating new resources with CrnkClient, the nested identifier must be setup in order to let CrnkClient access the parentId.
- Being experimental.

