
anchor:setup[]

# Setup

There are two main, orthogonal aspects of Crnk that need configuration:

1. The integration into a web framework like JAXRS or the Servlet API to be able to process requests.
2. The discovery of repositories, modules, exception mappers, etc.

The subsequent sections explain various possiblities resp. how to implement an own one.


## Requirements

Crnk library requires minimum Java 7 to build and run.



## Integration with JAX-RS

Crnk allows integration with JAX-RS environments through the usage of JAX-RS specification. JAX-RS 2.0 is
required for this integration. Under the hood there is a @PreMatching filter which checks each request for
JSON API processing. The Setup can look as simple as:

### CrnkFeature

[source]
----
@ApplicationPath("/")
	public class MyApplication extends Application {

		@Override
		public Set<Object> getSingletons() {
			CrnkFeature crnkFeature = new CrnkFeature();
			return Collections.singleton((Object)crnkFeature);
		}
	}
----

`CrnkFeature` provides various accessors to customize the behavior of Crnk.
A more advanced setup may look like:

[source]
----
	public class MyAdvancedCrnkFeature implements Feature {

		@Inject
		private EntityManager em;

		@Inject
		private EntityManagerFactory emFactory;

		...

		@Override
		public boolean configure(FeatureContext featureContext) {
			// also map entities to JSON API resources (see further below)
			JpaModule jpaModule = new JpaModule(emFactory, em, transactionRunner);
			jpaModule.setRepositoryFactory(new ValidatedJpaRepositoryFactory());

			// JSON API compliant URL handling with QuerySpec
			DefaultQuerySpecDeserializer querySpecDeserializer = new DefaultQuerySpecDeserializer();

			// limit all incoming requests to 20 resources if not specified otherwise
			querySpecDeserializer.setDefaultLimit(20L);

			ServiceLocator serviceLocator = ...
			CrnkFeature feature = new CrnkFeature(new ObjectMapper(), querySpecDeserializer, serviceLocator);
			feature.addModule(jpaModule);

			featureContext.register(feature);
			return true;
		}
	}
----

Note that depending on the discovery mechanism in use (like Spring or CDI), modules like this JpaModule can be picked
up automatically.

### Exception mapping for JAX-RS services

In many cases Crnk repositories are used along regular JAX-RS services. In such scenarios it can be worthwhile
if Crnk repositories and JAX-RS services make use of the same exception handling and response format. To make
use of the JSON API resp. Crnk exception handling in JAX-RS services, one can add the
*JsonapiExceptionMapperBridge* to the JAX-RS application. The constructor of `JsonapiExceptionMapperBridge`
takes `CrnkFeature` as parameter.

For an example have a look at the next section which make use of it together with `JsonApiResponseFilter`.


### Use JSON API format with JAX-RS services

Similar to `JsonapiExceptionMapperBridge` in the previous section, it is possible for JAX-RS services to return
resources in JSON API format with *JsonApiResponseFilter*. `JsonApiResponseFilter` wraps primitive
responses with a `data` object; resource objects with `data` and `included` objects.
The constructor of `JsonApiResponseFilter` takes `CrnkFeature` as parameter.


To determine which JAX-RS services should be wrapped, `JsonApiResponseFilter` checks whether the
`@Produce` annotation delivers JSON API. The produce
annotation can be added, for example, to the class:

[source]
.ScheduleRepository.java
----
include::../../../../crnk-test/src/main/java/io/crnk/test/mock/repository/ScheduleRepository.java[tags=annotation]
----

And the JAX-RS application setup looks like:

[source]
.JsonApiResponseFilterTestBase.java
----
include::../../../../crnk-rs/src/test/java/io/crnk/rs/JsonApiResponseFilterTestBase.java[tags=docs]
----

Note that:

- `CrnkProperties.NULL_DATA_RESPONSE_ENABLED` determines whether null responses should be wrapped
   as JSON API responses.
- Make use of proper service discovery instead of `CrnkProperties.RESOURCE_SEARCH_PACKAGE` in real applications.


### JAX-RS interoperability

Note that it is possible to implement repositories that host both JAX-RS and JSON-API methods to complement JSON
API repositories with non-resource based services. Have a look at the <<client_jaxrs,Crnk Client chapter>> for an example.


## Integration with Servlet API

There are two ways of integrating crnk using Servlets:

* Adding an instance of ``AbstractCrnkServlet``
* Adding an instance of ``AbstractCrnkFilter``

### Integrating using a Servlet

There is a `CrnkServlet` implementation allowing to integrate Crnk into a Servlet environment.
It can be configured with all the parameters outlined in the subsequent sections. Many times
application will desire to do more advanced customizations, in this case one can
extends `CrnkServlet` and get access to `CrnkBoot`. The code below shows a sample implementation:

[source]
.SampleCrnkServlet.java
----
include::../../../../crnk-servlet/src/test/java/io/crnk/servlet/SampleCrnkServlet.java[tags=docs]
----

The newly created servlet must be added to the ``web.xml`` file or to another deployment descriptor.
The code below shows a sample ``web.xml`` file with a properly defined and configured servlet:

[source]
----
  <web-app>
    <servlet>
      <servlet-name>SampleCrnkServlet</servlet-name>
      <servlet-class>io.crnk.servlet.SampleCrnkServlet</servlet-class>
      <init-param>
        <param-name>crnk.config.core.resource.package</param-name>
        <param-value>io.crnk.servlet.resource</param-value>
      </init-param>
    </servlet>
    <servlet-mapping>
      <servlet-name>SampleCrnkServlet</servlet-name>
      <url-pattern>/api/v1/ *</url-pattern>
    </servlet-mapping>
  </web-app>
----

You may omit the `resourceSearchPath` depending on which discovery mechanism is in place (see below).


### Integrating using a filter

Integrating Crnk as a Servlet filter works in a very similar fashion as for servlets:

[source]
.SampleCrnkFilter.java
----
include::../../../../crnk-servlet/src/test/java/io/crnk/servlet/SampleCrnkFilter.java[tags=docs]
----

The newly created filter must be added to ``web.xml`` file or other deployment descriptor.
A code below shows a sample ``web.xml`` file with properly defined and configured filter

[source]
----
  <web-app>
    <filter>
      <filter-name>SampleCrnkFilter</filter-name>
      <filter-class>io.crnk.servlet.SampleCrnkFilter</filter-class>
      <init-param>
        <param-name>crnk.config.core.resource.package</param-name>
        <param-value>io.crnk.servlet.resource</param-value>
      </init-param>
    </filter>
  </web-app>
----

## Integration with Spring and String Boot

Crnk provides with `crnk-spring` a number of utilities to seamlessly integrate with Spring and Spring Boot.
First and foremost, there is a ``CrnkConfigV3`` configuration class to hook Crnk into Spring Web to serve requests.
The web integration can be customized with the subsequent properties:

[source]
.application.properties
----
  crnk.domainName=http://localhost:8080
  crnk.pathPrefix=/api
----

Spring integration uses crnk-servlet ``AbstractCrnkFilter`` to fetch the requests. Similar to CDI, repositories
and modules are picked up from the Spring ApplicationContext with  ``SpringServiceDiscovery``.

Next to the Spring Web integration, `crnk-spring` provides a number modules to hook into other Spring components.
For a detailed overview see <<spring_modules,Spring modules>>.



## Discovery with CDI

To enable CDI support, add ``io.crnk:crnk-cdi`` to your classpath. Crnk will then pickup the
``CdiServiceDiscovery`` implementation and use it to discover its modules and repositories. Modules, repositories,
etc. will then be picked up if they are registered as CDI beans.

By default `Cdi.current()` is used to obtain a `BeanManager`. The application may also make use of
`CdiServiceDiscovery.setBeanManager(...)` to set a custom one. The various integrations like `CrnkFeature` provide
a `setServiceDiscovery` method to set a customized instance.

WARN: `Cdi.current()` has shown to be unreliable in some cases when doing EAR deployment. In such cases
it is highly recommended to set the `BeanManager manually`.

## Discovery with Guice

A `GuiceServiceDiscovery` implementation is provided. The various integrations like `CrnkFeature` provide
a `setServiceDiscovery` method to set the instance. For an example have a look at the dropwizard example
application (https://github.com/crnk-project/crnk-framework/tree/master/crnk-examples/dropwizard-simple-example).


## Discovery with Spring

The Spring integration comes with a ``SpringServiceDiscovery`` that makes use of the Spring `ApplicationContext`
to discover beans.


## Discovery without a dependency injection framework

If no dependency injection framework is used, Crnk can also discover beans on its own. For this purpose,
the `org.reflections:reflections` library has to be added to the classpath and the
`CrnkProperties.RESOURCE_SEARCH_PACKAGE` be defined. In JAX-RS this may look like:

[source]
----
@ApplicationPath("/")
	public class MyApplication extends Application {

		@Override
        public Set<Object> getSingletons() {
            CrnkFeature crnkFeature = new CrnkFeature();
            crnkFeature.getBoot().setServiceLocator(...);
            return Collections.singleton((Object)crnkFeature);
        }

		@Override
        public Map<String, Object> getProperties() {
            Map<String, Object> map = new HashMap<>();
            map.put(CrnkProperties.RESOURCE_SEARCH_PACKAGE, "com.myapplication.model")
            return map;
        }
	}
----

A `JsonServiceLocator` service locator can be provided to control the instatiation of object. By default the default
constructor will be used. The `CrnkProperties.RESOURCE_SEARCH_PACKAGE` property is passed to define which package
should be searched for beans. Multiple packages can be passed by specifying a comma separated string
of packages i.e. com.company.service.dto,com.company.service.repository. It will pick up any public non-abstract
class that makes use of Crnk interfaces, like repositories, exception mappers and modules.

## No Discovery

It is also possible to make use of no discovery mechanism at all. In this case it is still possible to add repositories
and other features through modules. Have a look at the various module related chapters.


## CrnkBoot

`CrnkBoot` is a class shared among all the different integrations that takes care of setting up and starting
Crnk. Every integration will provide access to it, which in turn allows for virtually any kind of customization.

Some possiblities:

- `getObjectMapper` allows access to the used Jackson instance.
- `addModule` allows to add a module.
- `setServiceDiscovery` sets a custom service discovery mechanism.
- `setPropertiesProvider` allows to set how properties are resolved.
- `getQuerySpecDeserializer` and `setQuerySpecDeserializer` allows to reconfigure how parameters are parsed.
   Note that in some areas JSON API only provides reocmmendations and Crnk follows those recommendations
   by default. So depending on your use cases, you may want to configure or implement some aspects differently.
- `setMaxPageLimit` allows to set the maximum number of allowed resources that can be fetched with a request
   by limiting pagination.
- `setDefaultPageLimit` allows to set a default page limit if none is specified by the request. *Highly
   recommended* to be used as people frequently browse repositories on there own with a web browser and
   fail to provide pagination. As a result, your entire database may get downloaded and may bring down
   your servers depending on the datasize.


## Parameters

Any of the integrations allows API access to customize Crnk. There are also a number of configuration flags
provided by `CrnkProperties`:

* `crnk.config.core.resource.domain`
  Domain name as well as protocol and optionally port number used when building links objects in responses i.e. http://crnk.io.
  The value must not end with ``/``. If the property is omitted, then they are extracted from the incoming request, which should work
  well for most use cases.

* `crnk.config.web.path.prefix`
  Default prefix of a URL path used in two cases:
  ** When building ``links`` objects in responses
  ** When performing method matching
  An example of a prefix ``/api/v1``.

* `crnk.config.include.paging.packagingEnabled` enables pagination for inclusions. Disabled by default. Be aware this may
  inadvertently enable pagination for included resources when doing paging on root resources if data structures
  are cyclic. See `CrnkProperties.INCLUDE_PAGING_ENABLED` fore mor information.

* `crnk.config.include.behavior` with possible values `BY_TYPE` (default) and `BY_ROOT_PATH`.
   `BY_ROOT_PATH` specifies that an inclusion can only requested as path from the root
   resource such as `include[tasks]=project.schedule`. While `BY_TYPE` can further request
   inclusions by type directly such as `include[tasks]=project&include[projects]=schedule`.
   For simple object structures they are semantically the same, but they do differ
   for more complex ones, like when multiple attributes lead
   to the same type or for cycle structures. In the later case BY_TYPE inclusions
   become recursive, while BY_ROOT_PATH do not. Note that the use of BY_TYPE
   outmatches BY_ROOT_PATH, so BY_TYPE includes everything BY_ROOT_PATH does
   and potentially more. For more information see `CrnkProperties.INCLUDE_BEHAVIOR`.

* `crnk.config.resource.immutableWrite` with values IGNORE (default) or FAIL.
  Determines how to deal with field that cannot be changed upon a PATCH or POST
  request. For more information see `CrnkProperties.RESOURCE_FIELD_IMMUTABLE_WRITE_BEHAVIOR`.

* `crnk.config.resource.response.return_404` with values true and false (default).
  Enforces a 404 response should a repository return a null value. This is common practice, but
  not strictly mandated by the JSON API specification. In general it is recommended for
  repository to throw `ResourceNotFoundException`.



